/* Microcontroller and computer boards. ids are stable keys for saved "have it" ticks and project needs.
   t = the short values used in the comparison table. */

const BOARDS = [
{ id:'uno', name:'Arduino UNO R3', family:'Arduino', level:'b', pinout:'uno',
  chip:'ATmega328P, 8-bit, 16MHz', logic:'5V', wireless:'None',
  gpio:'14 digital (6 PWM) + 6 analog', adc:'6 × 10-bit, 0–5V (0–1023)',
  memory:'32KB flash · 2KB RAM · 1KB EEPROM', power:'USB 5V, or 7–12V on the barrel jack / VIN', usb:'USB-B',
  desc:'The standard learning board. 5V logic matches most beginner modules, it is hard to damage, and nearly every tutorial and shield is written for it.',
  best:'Learning circuits and code, breadboard experiments, shields, 5V sensors and modules.',
  t:{ wireless:'—', gpio:'20', adc:'6 (10-bit)', best:'Learning' },
  pins:[
    ['D0 / D1', 'Hardware serial RX / TX, shared with USB. Keep them free while uploading.'],
    ['D2, D3', 'External interrupts — use for encoders, flow sensors and fast pulses.'],
    ['~3, 5, 6, 9, 10, 11', 'PWM outputs for analogWrite() (dimming, motor speed).'],
    ['A4 / A5', 'I2C SDA / SCL — also repeated on the two pins beside AREF.'],
    ['10 / 11 / 12 / 13', 'SPI SS / MOSI / MISO / SCK. D13 also drives the on-board LED.'],
    ['A0–A5', 'Analog inputs (0–1023 for 0–5V). They also work as digital pins.'],
    ['3.3V pin', 'Only about 50mA — fine for small 3.3V sensors, not for Wi-Fi modules.'],
  ],
  watch:[
    'Keep each pin under 20mA (40mA is the absolute maximum) and the whole chip under 200mA.',
    'Never drive motors, relay coils or LED strips straight from a pin — use a transistor or a driver board.',
    'The UNO R4 (Minima / WiFi) uses a different 32-bit chip. Most sketches work, but some libraries don’t.',
  ] },

{ id:'nano', name:'Arduino Nano', family:'Arduino', level:'b',
  chip:'ATmega328P, 8-bit, 16MHz', logic:'5V', wireless:'None',
  gpio:'14 digital (6 PWM) + 8 analog', adc:'8 × 10-bit (A6, A7 are analog-only)',
  memory:'32KB flash · 2KB RAM · 1KB EEPROM', power:'USB 5V, or 7–12V on VIN', usb:'Mini-USB or USB-C (clones)',
  desc:'An UNO in a small, breadboard-friendly package, with two extra analog inputs.',
  best:'Compact and permanent builds, breadboard projects.',
  t:{ wireless:'—', gpio:'22', adc:'8 (10-bit)', best:'Small 5V builds' },
  pins:[
    ['A4 / A5', 'I2C SDA / SCL.'],
    ['A6 / A7', 'Analog input only — no digitalRead/digitalWrite.'],
    ['D2, D3', 'External interrupts.'],
    ['~3, 5, 6, 9, 10, 11', 'PWM outputs, same as the UNO.'],
  ],
  watch:[
    'Most clones use a CH340 USB chip — install its driver if no port appears.',
    'If uploading fails, select “ATmega328P (Old Bootloader)” in the Arduino IDE.',
    'Nano Every, Nano 33 and Nano ESP32 are different boards despite the name.',
  ] },

{ id:'mega', name:'Arduino Mega 2560', family:'Arduino', level:'i',
  chip:'ATmega2560, 8-bit, 16MHz', logic:'5V', wireless:'None',
  gpio:'54 digital (15 PWM) + 16 analog', adc:'16 × 10-bit',
  memory:'256KB flash · 8KB RAM · 4KB EEPROM', power:'USB 5V, or 7–12V on the barrel jack / VIN', usb:'USB-B',
  desc:'The big Arduino: lots of pins and four hardware serial ports.',
  best:'Projects with many inputs and outputs, several serial devices at once (GPS + Bluetooth + display), 3D printers (RAMPS).',
  t:{ wireless:'—', gpio:'70', adc:'16 (10-bit)', best:'Lots of I/O' },
  pins:[
    ['20 / 21', 'I2C SDA / SCL — not A4 / A5 as on the UNO.'],
    ['50 / 51 / 52 / 53', 'SPI MISO / MOSI / SCK / SS.'],
    ['Serial1 · 2 · 3', 'TX/RX on 18/19, 16/17 and 14/15.'],
    ['2, 3, 18, 19, 20, 21', 'External interrupts.'],
  ],
  watch:[
    'Shields that expect I2C on A4/A5 don’t connect on the Mega — wire them to 20/21.',
  ] },

{ id:'nodemcu', name:'NodeMCU ESP8266 (ESP-12E)', family:'ESP', level:'i',
  chip:'ESP8266, 32-bit, 80/160MHz', logic:'3.3V', wireless:'Wi-Fi 2.4GHz',
  gpio:'About 11 usable', adc:'1 × 10-bit (A0, 0–3.3V on this board)',
  memory:'4MB flash · about 50KB free RAM', power:'USB 5V, or 5V on VIN', usb:'Micro-USB (CP2102 or CH340)',
  desc:'The cheap Wi-Fi board that started the IoT hobby. Still fine for simple connected sensors.',
  best:'Simple Wi-Fi sensors and switches with one analog input.',
  t:{ wireless:'Wi-Fi', gpio:'11', adc:'1 (10-bit)', best:'Simple Wi-Fi' },
  pins:[
    ['D0 = GPIO16', 'Wakes from deep sleep. No PWM or I2C.'],
    ['D1 = GPIO5', 'I2C SCL (default).'],
    ['D2 = GPIO4', 'I2C SDA (default).'],
    ['D3 = GPIO0', 'Boot pin — must be HIGH at start-up.'],
    ['D4 = GPIO2', 'On-board LED. Must be HIGH at start-up.'],
    ['D5 / D6 / D7', 'GPIO14 / 12 / 13 — SPI SCK / MISO / MOSI.'],
    ['D8 = GPIO15', 'Boot pin — must be LOW at start-up.'],
    ['A0', 'The only analog input.'],
  ],
  watch:[
    'Pins are 3.3V and not officially 5V tolerant.',
    'The D-labels are not GPIO numbers: D1 is GPIO5. Use the D1 constant in Arduino code.',
    'Only one analog input and no Bluetooth — for new projects an ESP32 is usually the better buy.',
  ] },

{ id:'esp32-devkit', name:'ESP32 DevKit V1 (30-pin)', family:'ESP', level:'i', pinout:'esp32-devkit',
  chip:'ESP32-WROOM-32, dual-core 32-bit, 240MHz', logic:'3.3V', wireless:'Wi-Fi 2.4GHz + Bluetooth Classic + BLE',
  gpio:'About 25 usable', adc:'12-bit — 6 ADC1 pins usable with Wi-Fi on',
  memory:'4MB flash · 520KB RAM', power:'USB 5V, or 5V on VIN (3V3 pin is the regulator output)', usb:'Micro-USB or USB-C (CP2102 or CH340)',
  desc:'The main board for your IoT stage: fast, Wi-Fi and Bluetooth, two DACs, capacitive touch pins, three UARTs and PWM on almost any pin.',
  best:'Wi-Fi sensor nodes, MQTT and web dashboards, Bluetooth, robots and RC cars.',
  t:{ wireless:'Wi-Fi + BT', gpio:'25', adc:'6 usable (12-bit)', best:'IoT (main choice)' },
  pins:[
    ['21 / 22', 'Default I2C SDA / SCL.'],
    ['23 / 19 / 18 / 5', 'Default SPI (VSPI) MOSI / MISO / SCK / SS.'],
    ['TX2 17 / RX2 16', 'Serial2 — a free hardware UART for GPS and other modules.'],
    ['34, 35, 36 (VP), 39 (VN)', 'Input only, with no internal pull-ups.'],
    ['32–39', 'ADC1 — use these for analog readings while Wi-Fi is on.'],
    ['25 / 26', 'DAC outputs: a real analog voltage, 0–3.3V.'],
    ['2', 'On-board blue LED on most DevKit V1 boards.'],
    ['4, 0, 2, 15, 13, 12, 14, 27, 33, 32', 'Capacitive touch inputs T0–T9 (touchRead()).'],
  ],
  watch:[
    'Every pin is 3.3V. 5V signals (HC-SR04 echo, 5V modules) need a divider or a level shifter.',
    'Boot pins 0, 2, 5, 12 and 15 set the start-up mode. GPIO12 must be LOW at boot or the board will not start.',
    'ADC2 pins (0, 2, 4, 12–15, 25–27) stop working for analogRead() while Wi-Fi is on.',
    'GPIO 6–11 are wired to the flash chip — never use them.',
    '30-pin and 38-pin DevKit boards have different pin orders. Check yours before wiring.',
    'The chip sleeps at about 10µA, but the board’s regulator and USB chip draw several mA — for batteries use a low-power board.',
    'If uploading hangs at “Connecting…”, hold the BOOT button until it starts.',
  ] },

{ id:'esp32-s3', name:'ESP32-S3 DevKitC-1', family:'ESP', level:'a',
  chip:'ESP32-S3, dual-core 32-bit, 240MHz', logic:'3.3V', wireless:'Wi-Fi 2.4GHz + BLE 5',
  gpio:'Up to 45', adc:'20 × 12-bit (ADC2 shared with Wi-Fi)',
  memory:'8–16MB flash, optional 2–8MB PSRAM', power:'USB 5V, or 5V pin', usb:'Two USB ports: native USB (OTG) and UART',
  desc:'The powerful ESP32: native USB, vector instructions for AI, camera and LCD interfaces, and optional PSRAM for big buffers.',
  best:'Cameras, colour displays, voice and TinyML, USB devices (keyboard, MIDI).',
  t:{ wireless:'Wi-Fi + BLE', gpio:'45', adc:'20 (12-bit)', best:'Camera, display, AI' },
  pins:[
    ['19 / 20', 'Native USB D− / D+.'],
    ['0, 3, 45, 46', 'Boot (strapping) pins.'],
    ['Any pin', 'I2C, SPI and UART can be assigned to most GPIOs.'],
  ],
  watch:[
    'No Bluetooth Classic — BLE only.',
    'Boards with octal PSRAM (N8R8, N16R8) reserve GPIO 35–37.',
  ] },

{ id:'esp32-c3', name:'ESP32-C3 (DevKitM / SuperMini)', family:'ESP', level:'i',
  chip:'ESP32-C3, single-core RISC-V, 160MHz', logic:'3.3V', wireless:'Wi-Fi 2.4GHz + BLE 5',
  gpio:'About 13–15', adc:'12-bit on GPIO 0–4',
  memory:'4MB flash · 400KB RAM', power:'USB 5V, or 5V pin', usb:'Native USB (no USB-serial chip)',
  desc:'A small, cheap, low-power ESP32 with fewer pins. Perfect for single-sensor Wi-Fi nodes.',
  best:'Small battery-friendly sensor nodes, BLE beacons, simple Wi-Fi switches.',
  t:{ wireless:'Wi-Fi + BLE', gpio:'13–15', adc:'5 (12-bit)', best:'Tiny sensor nodes' },
  pins:[
    ['0–4', 'ADC inputs — use these for analog sensors.'],
    ['2, 8, 9', 'Boot pins. GPIO9 is the BOOT button.'],
    ['8', 'On-board LED on many boards.'],
  ],
  watch:[
    'For Serial.print() over the native USB, set “USB CDC On Boot: Enabled” in the Arduino IDE.',
    'Single core and few pins — fine for sensor nodes, not for heavy multi-tasking.',
  ] },

{ id:'esp32-c6', name:'ESP32-C6', family:'ESP', level:'a',
  chip:'ESP32-C6, RISC-V, 160MHz', logic:'3.3V', wireless:'Wi-Fi 6 + BLE 5 + Zigbee / Thread',
  gpio:'About 30', adc:'7 × 12-bit',
  memory:'4–8MB flash · 512KB RAM', power:'USB 5V', usb:'Native USB + UART',
  desc:'The smart-home ESP32: adds an 802.15.4 radio for Zigbee and Thread, the networks used by Matter devices.',
  best:'Matter, Zigbee and Thread smart-home devices; Wi-Fi 6 networks.',
  t:{ wireless:'Wi-Fi 6 + BLE + Zigbee', gpio:'30', adc:'7 (12-bit)', best:'Smart home (Matter)' },
  pins:[],
  watch:[ 'A newer chip — check that the libraries you need support it.' ] },

{ id:'pico', name:'Raspberry Pi Pico / Pico W', family:'RP2040', level:'i', pinout:'pico',
  chip:'RP2040, dual-core Cortex-M0+, 133MHz', logic:'3.3V', wireless:'None (Pico W: Wi-Fi 2.4GHz + BLE)',
  gpio:'26', adc:'3 × 12-bit (GP26–28)',
  memory:'2MB flash · 264KB RAM', power:'USB 5V, or 1.8–5.5V on VSYS', usb:'Micro-USB',
  desc:'Cheap and well documented, excellent for MicroPython. Its PIO state machines generate precise signals in hardware.',
  best:'Learning MicroPython, precise timing (PIO), cheap Wi-Fi with the Pico W.',
  t:{ wireless:'Pico W: Wi-Fi + BLE', gpio:'26', adc:'3 (12-bit)', best:'MicroPython, timing' },
  pins:[
    ['GP26–28', 'ADC0–2 analog inputs.'],
    ['VSYS', '1.8–5.5V power input — good for batteries.'],
    ['3V3(OUT)', '3.3V output for sensors, up to about 300mA.'],
    ['LED', 'GP25 on the Pico. On the Pico W the LED is on the wireless chip — use "LED" in code.'],
    ['I2C / SPI / UART', 'Available on many different pin pairs.'],
  ],
  watch:[
    'Not 5V tolerant.',
    'Hold BOOTSEL while plugging in USB and it appears as a drive — copy the .uf2 firmware onto it.',
    'The Pico 2 / Pico 2 W use the newer, faster RP2350.',
  ] },

{ id:'rpi', name:'Raspberry Pi 4 / 5', family:'Linux', level:'a',
  chip:'Quad-core ARM, 1.8–2.4GHz, runs Linux', logic:'3.3V GPIO', wireless:'Wi-Fi + Bluetooth + Ethernet',
  gpio:'40-pin header (28 GPIO)', adc:'None — add an ADS1115',
  memory:'2–8GB RAM · microSD or SSD', power:'5V USB-C, 3A (Pi 4) / 5A (Pi 5)', usb:'USB-A host ports',
  desc:'A full computer, not a microcontroller. In an IoT system it is the hub that your ESP32 nodes report to.',
  best:'MQTT broker (Mosquitto), Node-RED, Home Assistant, databases and dashboards.',
  t:{ wireless:'Wi-Fi + BT + Ethernet', gpio:'28', adc:'—', best:'IoT hub / server' },
  pins:[],
  watch:[
    'No analog inputs.',
    'Shut it down properly — pulling the power can corrupt the SD card.',
    'GPIO pins are 3.3V and easily damaged by 5V.',
  ] },
];

const BOARD_CHOICE = [
  ['Learning circuits and code', 'uno'],
  ['A Wi-Fi sensor or dashboard project', 'esp32-devkit'],
  ['A tiny battery sensor node', 'esp32-c3'],
  ['Camera, colour display or voice', 'esp32-s3'],
  ['Zigbee / Matter smart home', 'esp32-c6'],
  ['MicroPython and precise timing', 'pico'],
  ['The hub that collects everything', 'rpi'],
];
