/* Breadboard exercises. "+5V" and "GND" mean the breadboard rails powered by the supply module (exercise 1).
   Each id is stable — it is the key for saved progress, so never reuse or rename one. */

const STAGES = [
  { id:1, title:'Power, resistors & LEDs' },
  { id:2, title:'Switches & logic' },
  { id:3, title:'Diodes & capacitors' },
  { id:4, title:'Transistors & MOSFETs' },
  { id:5, title:'Sensors' },
  { id:6, title:'555 timer' },
  { id:7, title:'ICs & displays' },
];

const EXERCISES = [
/* ---------- Stage 1 ---------- */
{ id:'supply', stage:1, title:'Set up and measure your 5V supply',
  goal:'Power the breadboard safely and confirm the rails really give 5V.',
  parts:['Full-size breadboard', 'Breadboard power supply module', '9V DC adapter', 'Digital multimeter'],
  steps:[
    'Plug the power module onto one end of the breadboard so its pins sit in the rails. Set both of its voltage jumpers to 5V.',
    'Connect the 9V adapter to the module’s barrel jack and switch it on — the module’s LED should light.',
    'Set the multimeter to DC volts. Black probe in a − rail hole, red probe in the + rail.',
    'Check both sides of the board, at both ends. Many long breadboards have a break halfway along each rail.',
  ],
  expect:'About 4.9–5.1V on every + rail section. A 0V reading means a rail break, or the module is plugged in the wrong way round.',
  why:'Every later exercise uses this 5V rail. Measuring before you build is the habit that saves the most debugging time.',
  pins:['breadboard'] },

{ id:'first-led', stage:1, title:'Light your first LED',
  goal:'Build the simplest complete circuit and see why an LED needs a resistor.',
  parts:['Red 5mm LED', '330Ω resistor', 'Jumper wires'],
  steps:[
    '+5V → 330Ω resistor → LED anode (long leg).',
    'LED cathode (short leg, flat side) → GND.',
    'Power on. If nothing lights, turn the LED around — it only conducts one way.',
    'Work out the current: (5V − 2V LED drop) ÷ 330Ω ≈ 9mA.',
  ],
  expect:'The LED glows steadily. Reversed, it stays dark but is not damaged.',
  why:'Never put an LED straight across 5V. Without a resistor nothing limits the current until the LED burns out.',
  pins:['led', 'breadboard'] },

{ id:'ohms-law', stage:1, title:'Measure current and brightness',
  goal:'Use Ohm’s law and see how the resistor value sets the current.',
  parts:['Red 5mm LED', '220Ω, 470Ω, 1kΩ and 10kΩ resistors', 'Digital multimeter'],
  steps:[
    'Build exercise 2, but leave a gap between the resistor and the LED anode.',
    'Set the meter to DC mA and move the red lead to the mA socket. Bridge the gap with the probes so the current flows through the meter.',
    'Record the current with 220Ω, 470Ω, 1kΩ and 10kΩ.',
    'Compare each reading with (5 − 2) ÷ R. Move the red lead back to the V socket when you finish.',
  ],
  expect:'Roughly 13mA, 6mA, 3mA and 0.3mA. The LED dims as the resistance rises and is only faintly visible at 10kΩ.',
  why:'To measure current you break the circuit and put the meter in series — the opposite of measuring voltage.',
  pins:['led'] },

{ id:'series-parallel', stage:1, title:'Series and parallel resistors',
  goal:'Measure how resistances add in series and combine in parallel.',
  parts:['1kΩ resistors ×3', '2.2kΩ resistor', 'Digital multimeter'],
  steps:[
    'With no power connected, put 1kΩ + 1kΩ + 2.2kΩ in series and measure across the whole chain on the Ω range.',
    'Connect the chain between +5V and GND. Measure the voltage across each resistor.',
    'Power off. Put two 1kΩ side by side with both ends shared and measure them. Add the third 1kΩ in parallel and measure again.',
  ],
  expect:'Series: about 4.2kΩ, with ≈1.19V, 1.19V and 2.62V across the resistors — adding up to 5V. Parallel: 500Ω with two, about 333Ω with three.',
  why:'Series resistances add; a parallel total is always smaller than the smallest resistor. Always measure resistance with the power off.',
  pins:['breadboard'] },

{ id:'divider', stage:1, title:'Voltage divider',
  goal:'Make a lower voltage from 5V with two resistors.',
  parts:['10kΩ resistors ×2', '4.7kΩ resistor', 'Digital multimeter'],
  steps:[
    '+5V → 10kΩ → middle node → 10kΩ → GND. Measure from the middle node to GND.',
    'Replace the bottom resistor with 4.7kΩ and measure again.',
    'Check both readings with Vout = Vin × R2 ÷ (R1 + R2), where R2 is the bottom resistor.',
  ],
  expect:'2.5V with two 10kΩ, and about 1.6V with 4.7kΩ at the bottom.',
  why:'Dividers are how you read sensors such as LDRs and thermistors, and how you set reference voltages for comparators.',
  pins:[] },

{ id:'pot-dimmer', stage:1, title:'Potentiometer: variable voltage and LED dimmer',
  goal:'Use a pot as an adjustable divider, then as a variable resistor.',
  parts:['10kΩ potentiometer', '220Ω resistor', 'Red 5mm LED', 'Digital multimeter'],
  steps:[
    'Outer pins of the pot to +5V and GND, middle pin (wiper) to the meter. Turn the knob end to end.',
    'Rewire: +5V → one outer pin, wiper → 220Ω → LED → GND. Leave the other outer pin unconnected.',
    'Turn the knob slowly from one end to the other.',
  ],
  expect:'The meter sweeps smoothly from 0 to 5V. As a dimmer, the LED goes from bright to very dim.',
  why:'The fixed 220Ω keeps the LED safe when the pot is at 0Ω. Always keep a fixed resistor in series with a variable one.',
  pins:['pot'] },

{ id:'led-series-parallel', stage:1, title:'LEDs in series and in parallel',
  goal:'See why LEDs in parallel each need their own resistor.',
  parts:['Red 5mm LEDs ×2', 'Blue 5mm LED', '150Ω resistor', '330Ω resistors ×2'],
  steps:[
    'Series: +5V → 150Ω → LED1 → LED2 → GND, anode to cathode each time. Measure the voltage across each LED.',
    'Parallel: give each red LED its own 330Ω from +5V, both cathodes to GND.',
    'Now try one red and one blue LED in parallel sharing a single 330Ω.',
  ],
  expect:'Series: both glow, with about 2V across each. Parallel with their own resistors: equally bright. Sharing one resistor: the red LED takes the current and the blue one stays dark or very dim.',
  why:'Different colours have different forward voltages. With one shared resistor, the LED with the lowest voltage hogs the current.',
  pins:['led'] },

{ id:'rgb-mix', stage:1, title:'RGB LED colour mixing',
  goal:'Mix red, green and blue light from one package.',
  parts:['RGB LED — common cathode', '330Ω resistors ×3', '1kΩ resistor', 'Jumper wires'],
  steps:[
    'Put the RGB LED on the board. The longest leg is common — connect it to GND.',
    'Connect a 330Ω resistor to each of the other three legs.',
    'With jumper wires, connect each resistor to +5V one at a time, then in pairs, then all three.',
    'Swap one 330Ω for 1kΩ and see how the mix shifts.',
  ],
  expect:'Red + green ≈ yellow, green + blue ≈ cyan, red + blue ≈ magenta, and all three ≈ white (often slightly blue).',
  why:'Microcontrollers mix colours the same way, using PWM instead of resistors to set each channel’s brightness.',
  pins:['rgb'] },

/* ---------- Stage 2 ---------- */
{ id:'push-button', stage:2, title:'Push-button switch',
  goal:'Control an LED with a momentary button and learn its 4-leg layout.',
  parts:['6×6mm tactile push button', '330Ω resistor', 'Green 5mm LED'],
  steps:[
    'Place the button across the centre gap of the breadboard.',
    '+5V → one leg of the button. The diagonally opposite leg → 330Ω → LED → GND.',
    'Press and release. Then try two legs on the same side to find which pairs are joined inside.',
  ],
  expect:'The LED is on only while the button is held down. On a joined pair of legs it stays on all the time.',
  why:'Knowing which legs are connected inside avoids the most common button wiring mistake.',
  pins:['button', 'breadboard'] },

{ id:'spdt', stage:2, title:'SPDT switch: choose between two LEDs',
  goal:'Route one supply to either of two outputs.',
  parts:['SPDT switch', 'Red 5mm LED', 'Green 5mm LED', '330Ω resistors ×2'],
  steps:[
    'The middle pin of the SPDT switch is common. Connect it to +5V.',
    'One outer pin → 330Ω → red LED → GND. The other outer pin → 330Ω → green LED → GND.',
    'Flip the switch back and forth.',
  ],
  expect:'Exactly one LED is on at a time, and the switch stays wherever you leave it.',
  why:'SPDT is the basis of selectors and changeover circuits — the same contact arrangement you will meet in relays.',
  pins:[] },

{ id:'pull-down', stage:2, title:'Floating inputs and pull-down resistors',
  goal:'See a floating logic input misbehave, then fix it with a resistor.',
  parts:['74HC04 (NOT)', '6×6mm tactile push button', '10kΩ resistor', '330Ω resistor', 'Red 5mm LED'],
  steps:[
    'Place the 74HC04 across the centre gap. Pin 14 → +5V, pin 7 → GND. Tie the unused inputs (pins 3, 5, 9, 11 and 13) to GND.',
    'Output 1Y (pin 2) → 330Ω → LED → GND.',
    '10kΩ from input 1A (pin 1) to GND, and the button from pin 1 to +5V. Press and release.',
    'Now remove the 10kΩ, and touch or wave your hand near the wire on pin 1.',
  ],
  expect:'With the pull-down: the LED is on when released and off when pressed. Without it: the LED flickers or changes when you touch the wire.',
  why:'Every button input needs a pull-up or pull-down resistor. Microcontroller pins are the same — that is why INPUT_PULLUP exists.',
  pins:['hc04'] },

{ id:'logic-gates', stage:2, title:'Logic gate truth tables',
  goal:'Check AND, OR, NAND and XOR with two buttons.',
  parts:['74HC08 (AND)', '74HC32 (OR)', '74HC00 (NAND)', '74HC86 (XOR)', 'Push buttons ×2', '10kΩ resistors ×2', '330Ω resistor', 'Red 5mm LED'],
  steps:[
    'Place the 74HC08. Pin 14 → +5V, pin 7 → GND. Tie unused inputs (pins 4, 5, 9, 10, 12, 13) to GND.',
    'Button A: +5V → button → pin 1, with 10kΩ from pin 1 to GND. Button B the same way on pin 2.',
    'Output pin 3 → 330Ω → LED → GND. Try all four button combinations and write down the truth table.',
    'Power off and swap in the 74HC32, 74HC00 and 74HC86 in turn — they share the same pinout.',
  ],
  expect:'AND: on only when both are pressed. OR: on with either. NAND: off only when both are pressed. XOR: on with exactly one.',
  why:'These four chips are pin-compatible, so one circuit tests them all. The 74HC02 (NOR) has a different pinout — check its diagram first.',
  pins:['hc-quad', 'hc02'] },

/* ---------- Stage 3 ---------- */
{ id:'diode-direction', stage:3, title:'Diode direction and forward voltage',
  goal:'See a diode block current one way and measure its voltage drop.',
  parts:['1N4001–1N4007 rectifier', '1N4148 signal diode', '1N5819 Schottky diode', '330Ω resistor', 'Red 5mm LED', 'Digital multimeter'],
  steps:[
    'Set the meter to diode test. Red probe on the anode, black on the striped end (cathode). Note the reading, then swap the probes.',
    'Repeat for the 1N4001, 1N4148 and 1N5819.',
    'Build: +5V → 1N4001 (stripe away from +5V) → 330Ω → LED → GND. Then turn the diode around.',
  ],
  expect:'About 0.5–0.7V for the 1N4001 and 1N4148, about 0.2–0.4V for the 1N5819, and OL when reversed. The LED lights only with the stripe facing away from +5V.',
  why:'This is reverse-polarity protection: a series diode stops a backwards battery from reaching your circuit.',
  pins:['diode'] },

{ id:'cap-fade', stage:3, title:'Capacitor as a tiny battery',
  goal:'Watch a capacitor store charge and release it slowly through an LED.',
  parts:['Electrolytic 470µF', 'Electrolytic 1000µF', '6×6mm tactile push button', '470Ω resistor', 'Yellow 5mm LED'],
  steps:[
    '+5V → button → node X.',
    'Node X → 470µF + leg (long leg). Its − leg (striped side) → GND.',
    'Node X → 470Ω → LED → GND.',
    'Hold the button for a second, then let go. Repeat with the 1000µF capacitor.',
  ],
  expect:'The LED stays lit after you let go and fades out over a second or so. With 1000µF it lasts about twice as long.',
  why:'More capacitance or more resistance makes the charge last longer — the idea behind every RC timer.',
  pins:['ecap', 'button'] },

{ id:'rc-time', stage:3, title:'Measure an RC time constant',
  goal:'Time how long a capacitor takes to charge through a resistor.',
  parts:['100kΩ resistor', 'Electrolytic 100µF', 'Digital multimeter', 'Phone stopwatch'],
  steps:[
    'With the power off, discharge the capacitor by shorting its legs with a wire.',
    '+5V → 100kΩ → capacitor + leg. Capacitor − leg → GND. Meter across the capacitor.',
    'Start the stopwatch as you switch on. Note the voltage at 10, 20, 30 and 50 seconds.',
  ],
  expect:'τ = R × C = 100kΩ × 100µF = 10s. About 3.2V at 10s (63%), 4.3V at 20s, 4.75V at 30s and nearly 5V by 50s. ±20% is normal for electrolytics.',
  why:'The 63% point at one time constant is the rule behind every 555 timer and filter you will design.',
  pins:['ecap'] },

{ id:'zener', stage:3, title:'Zener voltage regulator',
  goal:'Hold a steady voltage from a 9V supply with a Zener diode.',
  parts:['Zener 5.1V', 'Zener 3.3V', '470Ω resistor', '1kΩ resistor', '9V battery clip or 9V DC adapter', 'Digital multimeter'],
  steps:[
    'Use a separate 9V supply for this one, not the 5V rail.',
    '9V + → 470Ω → node → Zener cathode (stripe). Zener anode → 9V −.',
    'Measure from the node to 9V −. Then add a 1kΩ load from the node to 9V − and measure again.',
    'Swap in the 3.3V Zener and repeat.',
  ],
  expect:'About 5.1V (4.9–5.3V) with or without the 1kΩ load, and about 3.3V with the other Zener.',
  why:'A Zener is fitted “backwards” on purpose. The resistor drops the difference between 9V and the Zener voltage.',
  pins:['diode'] },

{ id:'regulator', stage:3, title:'LM7805 fixed regulator',
  goal:'Build a proper, stable 5V supply from 9V.',
  parts:['LM7805 5V regulator', 'Electrolytic 10µF ×2', 'Ceramic 100nF', '9V battery clip or 9V DC adapter', 'Red 5mm LED', '330Ω resistor', 'Digital multimeter'],
  steps:[
    'With the printed side facing you, the pins are IN, GND, OUT.',
    '9V + → IN, 9V − → GND. Put 10µF from IN to GND, and 10µF plus 100nF from OUT to GND, close to the pins.',
    'Measure OUT to GND, then connect the LED and 330Ω as a load and measure again.',
  ],
  expect:'5.0V (±0.2V) at the output, unchanged when the LED is connected. The regulator stays cool at this small load.',
  why:'A 7805 needs its input at least about 7V. The voltage it drops turns into heat, which matters once you draw real current.',
  pins:['lm78xx', 'ecap'] },

/* ---------- Stage 4 ---------- */
{ id:'npn-switch', stage:4, title:'NPN transistor switch',
  goal:'Use a small base current to switch a larger LED current.',
  parts:['BC547 (NPN)', '10kΩ resistor', '100kΩ resistor', '330Ω resistor', '6×6mm tactile push button', 'Red 5mm LED'],
  steps:[
    'BC547 with the flat face toward you: C, B, E from left to right.',
    '+5V → 330Ω → LED → collector. Emitter → GND.',
    '+5V → button → 10kΩ → base. Add 100kΩ from base to GND so it can’t float.',
    'Press the button. Measure the base current and the collector current (meter in series) and compare.',
  ],
  expect:'The LED lights while you press. Base current ≈ 0.4mA, collector current ≈ 9mA — a small current controlling a larger one.',
  why:'This low-side switch is how a microcontroller pin drives buzzers, relays and motors it could never power directly.',
  pins:['bc547', 'pn2222'] },

{ id:'darlington-touch', stage:4, title:'Darlington touch switch',
  goal:'Chain two transistors to amplify the tiny current through your finger.',
  parts:['BC547 (NPN) ×2', '1kΩ resistor', '330Ω resistor', 'Red 5mm LED', 'Jumper wires ×2 (touch pads)'],
  steps:[
    '+5V → 330Ω → LED → both collectors (join them).',
    'Emitter of transistor 1 → base of transistor 2. Emitter of transistor 2 → GND.',
    'Base of transistor 1 → 1kΩ → a loose jumper wire (pad A). A second loose jumper from +5V is pad B.',
    'Touch the ends of pad A and pad B together with one fingertip.',
  ],
  expect:'The LED turns on while your finger bridges the pads, and glows brighter if you press harder or dampen your finger.',
  why:'The gains multiply (about 200 × 200), so microamps through your skin can switch milliamps.',
  pins:['bc547'] },

{ id:'pnp-switch', stage:4, title:'PNP high-side switch',
  goal:'Switch the positive side of a load with a PNP transistor.',
  parts:['BC557 (PNP)', '10kΩ resistor', '100kΩ resistor', '330Ω resistor', '6×6mm tactile push button', 'Green 5mm LED'],
  steps:[
    'BC557 with the flat face toward you: C, B, E (same order as the BC547).',
    'Emitter → +5V. Collector → 330Ω → LED → GND.',
    'Base → 10kΩ → button → GND. Add 100kΩ from base to +5V to hold it off.',
    'Press the button.',
  ],
  expect:'The LED turns on when the button pulls the base LOW — the reverse of the NPN circuit.',
  why:'PNP transistors and P-channel MOSFETs sit between the supply and the load, so the load’s ground connection stays solid.',
  pins:['bc557', 'pn2907'] },

{ id:'mosfet-switch', stage:4, title:'MOSFET switch and gate charge',
  goal:'Switch an LED with a MOSFET and see why its gate needs a pull-down.',
  parts:['2N7000 (N-channel)', '100kΩ resistor', '330Ω resistor', 'Red 5mm LED', 'Jumper wire'],
  steps:[
    '2N7000 with the flat face toward you: S, G, D from left to right.',
    '+5V → 330Ω → LED → drain. Source → GND.',
    'Put a jumper on the gate. Touch its free end to +5V, then pull it away and leave it floating.',
    'Touch the free end to GND. Then add 100kΩ from gate to GND and repeat.',
  ],
  expect:'Without the pull-down the LED stays on after you let go — the gate holds its charge — until you touch the wire to GND. With 100kΩ it turns off as soon as you let go.',
  why:'A gate draws almost no current, which is efficient but means it must be held at a known level. Careful: the BS170 has its pins reversed.',
  pins:['2n7000', 'bs170'] },

/* ---------- Stage 5 ---------- */
{ id:'night-light', stage:5, title:'Automatic night light',
  goal:'Turn an LED on automatically when it gets dark.',
  parts:['LDR (light-dependent resistor)', 'BC547 (NPN)', '10kΩ resistor', '330Ω resistor', 'White 5mm LED'],
  steps:[
    '+5V → 330Ω → LED → BC547 collector. Emitter → GND.',
    '+5V → 10kΩ → base.',
    'LDR from base to GND.',
    'Cover the LDR with your hand, then shine a torch on it.',
  ],
  expect:'In normal room light the LED is off or dim. Covering the LDR turns it fully on.',
  why:'The LDR and the 10kΩ form a voltage divider that sets the base voltage — the same idea as exercise 5.',
  pins:['bc547'] },

{ id:'thermistor', stage:5, title:'Thermistor temperature sensor',
  goal:'Read temperature as a voltage.',
  parts:['NTC 10k thermistor', '10kΩ resistor', 'Digital multimeter'],
  steps:[
    '+5V → thermistor → middle node → 10kΩ → GND.',
    'Measure the node voltage at room temperature.',
    'Hold the thermistor between your fingers for 30 seconds and watch the reading.',
    'Swap the thermistor and the resistor and repeat.',
  ],
  expect:'About 2.5V at 25°C. Warming it makes the voltage rise; with the parts swapped it falls instead.',
  why:'An NTC’s resistance falls as it warms. An Arduino reads exactly this voltage on an analog pin to work out the temperature.',
  pins:[] },

{ id:'ir-beam', stage:5, title:'Infrared beam sensor',
  goal:'Detect an invisible IR beam with a photodiode.',
  parts:['IR LED', 'Photodiode', '220Ω resistor', '100kΩ resistor', 'Digital multimeter', 'Phone camera'],
  steps:[
    '+5V → 220Ω → IR LED anode (long leg), cathode → GND. Look at it through your phone camera to check it is on.',
    'Photodiode reverse-biased: cathode → +5V, anode → node → 100kΩ → GND. Use diode test to find the cathode if unsure.',
    'Point the IR LED at the photodiode from 1–2cm away and measure the node voltage.',
    'Slide a piece of card between them.',
  ],
  expect:'The node voltage rises (often 1–4V) when the beam hits the photodiode and drops near 0V when you block it.',
  why:'Beam-break counters, IR remotes and line-following sensors all use this emitter and detector pair.',
  pins:['led'] },

/* ---------- Stage 6 ---------- */
{ id:'555-astable', stage:6, title:'555 LED blinker (astable)',
  goal:'Make LEDs flash on their own with the 555 timer.',
  parts:['NE555 / LM555 timer', '10kΩ resistor', '47kΩ resistor', 'Electrolytic 10µF', 'Ceramic 10nF', '330Ω resistors ×2', 'Red 5mm LED', 'Green 5mm LED', '8-pin DIP socket (optional)'],
  steps:[
    'Pin 8 → +5V, pin 1 → GND, pin 4 (RESET) → +5V, pin 5 → 10nF → GND.',
    '+5V → 10kΩ → pin 7. Pin 7 → 47kΩ → pin 6. Join pins 6 and 2.',
    'Pin 2 → 10µF + leg. Capacitor − leg → GND.',
    'Pin 3 → 330Ω → red LED → GND. Then +5V → 330Ω → green LED anode, green LED cathode → pin 3.',
  ],
  expect:'Red and green flash alternately about 1.4 times a second: f = 1.44 ÷ ((R1 + 2·R2) × C) = 1.44 ÷ (104kΩ × 10µF).',
  why:'Swap the 10µF for 1µF and it runs 10× faster. This circuit is the clock behind countless blinkers and counters.',
  pins:['ne555', 'ecap'] },

{ id:'555-monostable', stage:6, title:'555 one-shot timer (monostable)',
  goal:'Press a button once and keep an LED on for a set time.',
  parts:['NE555 / LM555 timer', '100kΩ resistor', '10kΩ resistor', 'Electrolytic 100µF', 'Ceramic 10nF', '6×6mm tactile push button', '330Ω resistor', 'Yellow 5mm LED'],
  steps:[
    'Pin 8 → +5V, pin 1 → GND, pin 4 → +5V, pin 5 → 10nF → GND.',
    'Pin 2 → 10kΩ → +5V to keep the trigger HIGH. Button from pin 2 to GND.',
    'Join pins 6 and 7. +5V → 100kΩ → pins 6/7. Pins 6/7 → 100µF + leg, − leg → GND.',
    'Pin 3 → 330Ω → LED → GND. Tap the button and time the LED.',
  ],
  expect:'After a short press the LED stays on for about 1.1 × R × C = 1.1 × 100kΩ × 100µF ≈ 11 seconds.',
  why:'Change R or C to set any delay. Stair lights, timeouts and button debouncers work this way.',
  pins:['ne555', 'button'] },

{ id:'555-tone', stage:6, title:'Tone generator and buzzers',
  goal:'Make adjustable tones with a 555 and compare active and passive buzzers.',
  parts:['NE555 / LM555 timer', '1kΩ resistors ×2', '10kΩ potentiometer', 'Ceramic 100nF', 'Ceramic 10nF', 'Passive piezo buzzer', '5V active buzzer'],
  steps:[
    'Build the astable from exercise 25 with R1 = 1kΩ, R2 = 1kΩ in series with the pot (wiper and one outer pin), and C = 100nF.',
    'Pin 3 → passive buzzer → GND. Turn the pot.',
    'Disconnect the 555. Connect the active buzzer straight across +5V and GND (mind its + mark), then the passive buzzer the same way.',
  ],
  expect:'With the 555, the passive buzzer sweeps from about 600Hz to 4.8kHz as you turn the pot. On plain DC the active buzzer beeps, but the passive one only clicks once.',
  why:'An active buzzer has its own oscillator; a passive one needs a changing signal. That is how microcontrollers play melodies.',
  pins:['ne555', 'pot'] },

/* ---------- Stage 7 ---------- */
{ id:'comparator', stage:7, title:'Op-amp light comparator',
  goal:'Use an op-amp to switch an LED cleanly at a light level you set.',
  parts:['LM358 op-amp', 'LDR (light-dependent resistor)', '10kΩ resistor', '10kΩ potentiometer', '330Ω resistor', 'Red 5mm LED'],
  steps:[
    'Pin 8 → +5V, pin 4 → GND. For the unused half, pin 5 → GND and join pins 6 and 7.',
    'Sensor divider: +5V → 10kΩ → node → LDR → GND. Node → pin 3 (IN+ A).',
    'Pot outer pins to +5V and GND, wiper → pin 2 (IN− A).',
    'Pin 1 (OUT A) → 330Ω → LED → GND. Turn the pot until the LED just goes off, then cover the LDR.',
  ],
  expect:'The LED snaps fully on when it gets darker than your set point and fully off when lighter — no gradual fade like exercise 22.',
  why:'A comparator output is only HIGH or LOW: whichever input is higher wins. Measure pins 2 and 3 to see it happen.',
  pins:['lm358', 'pot'] },

{ id:'4017-chaser', stage:7, title:'LED chaser with CD4017',
  goal:'Drive ten LEDs in sequence with a 555 clock and a decade counter.',
  parts:['CD4017 decade counter', 'The 555 blinker from exercise 25', '5mm LEDs ×10 (mixed)', '330Ω resistor', '16-pin DIP socket (optional)'],
  steps:[
    'Build the 555 astable from exercise 25. Its own LEDs are optional.',
    'CD4017: pin 16 → +5V, pin 8 → GND, pin 13 (CLK INH) → GND, pin 15 (RESET) → GND.',
    '555 pin 3 → CD4017 pin 14 (CLK).',
    'Outputs in order: Q0 pin 3, Q1 pin 2, Q2 pin 4, Q3 pin 7, Q4 pin 10, Q5 pin 1, Q6 pin 5, Q7 pin 6, Q8 pin 9, Q9 pin 11. Each → one LED anode.',
    'Join all ten LED cathodes → one shared 330Ω → GND.',
  ],
  expect:'A single light steps along the ten LEDs, one step per 555 pulse, then wraps back to the first.',
  why:'Only one output is ever HIGH, so one shared resistor is enough. Move RESET from GND to Q5 (pin 1) and it counts to 5 instead.',
  pins:['cd4017', 'ne555'] },

{ id:'7-segment', stage:7, title:'7-segment display',
  goal:'Light the segments of a raw display and form digits by hand.',
  parts:['7-segment display — common cathode', '330Ω resistors ×8', 'DIP switch', 'Digital multimeter'],
  steps:[
    'Find the pins: diode-test mode, black probe on a COM pin (3 or 8), red probe on each other pin — each lights one segment.',
    'COM pin → GND.',
    'Each segment pin (a–g and dp) → its own 330Ω → one side of the DIP switch. The other side of every switch → +5V.',
    'Switch segments on to make the digits 0–9. For example 1 = b + c, 7 = a + b + c, 8 = all seven.',
  ],
  expect:'Each switch lights one segment, and every segment is equally bright whichever digit you show.',
  why:'One resistor per segment keeps the brightness even. A 74HC595 or a microcontroller does this same job for you later — just much faster.',
  pins:['seg7'] },
];
