/* Starter electronics kit — the complete buy list, with what each part is, where it is used and when you need it.
   Item: [name, qty, when, description, stars?]   when: key of KIT_WHEN.   stars: priority 1–5 (tools only). */

const KIT_WHEN = {
  1:'Day 1',
  2:'Breadboard basics',
  3:'Arduino stage',
  4:'ESP32 & IoT',
  5:'Robotics',
  6:'Later',
};

const KIT_SECTIONS = [
{ n:1, title:'Essential tools', intro:'The tools you use on every single circuit.',
  notes:[['key', 'A decent multimeter is more important than buying an expensive Arduino or ESP32 board.']],
  items:[
    ['Digital multimeter', '1', 1, 'Measures voltage, current and resistance, checks continuity and tests diodes. You use it in almost every exercise: checking a supply before connecting parts, finding wiring mistakes and confirming resistor values.', 5],
    ['Soldering iron, temperature-controlled', '1', 3, 'Melts solder to join parts permanently. You need it sooner than you think — many sensor modules arrive with their header pins loose. Temperature control (about 330–350°C) avoids burnt pads and cold joints.', 4],
    ['Soldering stand', '1', 3, 'Holds the hot iron safely between joints, with a sponge or brass wool to clean the tip. Never lay a hot iron on the bench.', 4],
    ['Solder wire', '1 roll', 3, 'Rosin-core electronics solder, 0.6–0.8mm. Leaded 63/37 is easiest to learn with; lead-free is safer to handle. Wash your hands after soldering either way.', 4],
    ['Desoldering pump', '1', 3, 'A spring-loaded vacuum that sucks molten solder off a joint — for removing a wrongly placed part or salvaging components.', 3],
    ['Solder wick', '1', 3, 'Braided copper that soaks up solder when heated. Cleans pads and removes solder bridges between close pins.', 3],
    ['Wire stripper', '1', 1, 'Removes insulation cleanly without nicking the copper. You cut and strip solid-core wire for neat breadboard layouts from the very first week.', 5],
    ['Side cutter / flush cutter', '1', 1, 'Cuts wire and component legs flush and clean — trimming LED and resistor legs so they sit neatly on the breadboard, and trimming legs after soldering.', 5],
    ['Long-nose pliers', '1', 1, 'Bend component legs, hold small parts, straighten header pins, and push parts into tight breadboard spots.', 4],
    ['Small precision screwdriver set', '1', 1, 'For screw terminals, the small blue trimpots on sensor modules, and tiny enclosure screws.', 4],
    ['Tweezers', '1 set', 2, 'Place and hold tiny parts — SMD components, jumper caps, small screws — and hold wires steady while soldering.', 3],
    ['Heat-shrink tubing, assorted', '1 set', 3, 'Slides over a soldered joint and shrinks with heat to insulate and strengthen it: wire splices, motor leads and battery connections.', 3],
    ['Electrical insulation tape', '1', 1, 'Quick insulation of exposed terminals, bundling and labelling wires. Use heat-shrink for permanent joints.', 3],
    ['Small component storage boxes', '3–5', 1, 'Compartment boxes that stop resistors, LEDs and ICs becoming one mixed pile. Set them up before your parts arrive.', 4],
    ['Jumper-wire tester / continuity tester', '1', 2, 'Quickly finds broken jumper wires — cheap Dupont wires fail more often than you would expect. Your multimeter’s continuity mode does the same job.', 2],
  ] },

{ n:2, title:'Breadboards & prototyping', intro:'The platform every circuit is built on, and the wires that connect it.',
  items:[
    ['Full-size solderless breadboard, 830-point', '2', 1, 'The main platform for every circuit — parts push into spring clips, no soldering. With two you can keep one circuit built while starting the next.'],
    ['Mini breadboard', '2', 2, '170-point boards for small sub-circuits, quick sensor tests, or sticking onto a robot chassis.'],
    ['Breadboard power supply module', '2', 1, 'Plugs onto the rails and gives regulated 5V and 3.3V from an adapter or USB. Powers most exercises; a second one runs another board, or 3.3V and 5V side by side.'],
    ['Breadboard jumper wire kit', '1', 1, 'Pre-cut, pre-bent solid wires in many lengths. They lie flat, so circuits stay tidy, reliable and easy to follow when debugging.'],
    ['Male-to-male Dupont wires', '1 set', 1, 'Flexible jumpers from breadboard to breadboard, or from the Arduino’s header sockets to the breadboard.'],
    ['Male-to-female Dupont wires', '1 set', 3, 'The male end goes into a breadboard or Arduino socket, the female end onto a module’s header pins — the usual way to connect sensor modules.'],
    ['Female-to-female Dupont wires', '1 set', 3, 'Join two sets of male header pins directly — module to module, or module to an ESP32 or Pico without a breadboard.'],
    ['Solid-core hookup wire', '1 set', 1, 'Single-strand wire (about 22 AWG) you cut to length. It pushes cleanly into breadboards and is used for permanent point-to-point wiring.'],
    ['2-pin terminal blocks', '10', 2, 'Screw terminals for connecting power leads, battery wires and motors firmly without soldering.'],
    ['3-pin terminal blocks', '10', 3, 'For three-wire connections such as sensors (VCC, GND, signal) and servos on your own boards.'],
    ['4-pin terminal blocks', '5', 4, 'For four-wire links such as I2C (VCC, GND, SDA, SCL) or the two coils of a stepper motor.'],
    ['Pin headers, male', '1 strip/set', 3, 'Solder onto modules and perfboard so they plug into breadboards or take Dupont wires. Snap off as many pins as you need.'],
    ['Pin headers, female', '1 strip/set', 3, 'Sockets for plugging in modules or boards — an ESP32 or Nano on perfboard stays removable and reusable.'],
  ] },

{ n:3, title:'Resistors', intro:'Don’t buy only a few individual resistors — get a large assortment kit.',
  notes:[['tip', 'Look for ¼W through-hole resistors, 1% or 5% tolerance. Preferably buy an E12/E24 assortment box containing hundreds of values.']],
  items:[
    ['E12 / E24 resistor assortment box', 'Hundreds', 1, 'The best single purchase: every standard value, so you never wait for a missing resistor. E12 has 12 values per decade, E24 has 24.'],
    ['10Ω', '10+', 2, 'Very low value: current sensing (measure the voltage across it), MOSFET gate resistors, and small current limits in power circuits.'],
    ['22Ω', '10+', 2, 'Series resistor for high-current or IR LEDs, and damping resistors on fast signal lines.'],
    ['47Ω', '10+', 2, 'Current limit for bright LEDs on 3.3V, and a series resistor for small speakers.'],
    ['100Ω', '10+', 1, 'MOSFET gate series resistor, series resistor for a passive buzzer or speaker, and protection on signal lines.'],
    ['220Ω', '10+', 1, 'The classic LED resistor on 5V (about 14mA), used throughout the Arduino lessons; also a safety resistor in series with pots.'],
    ['330Ω', '10+', 1, 'LED resistor on 5V at a gentler 9mA — used in most breadboard exercises and for each segment of a 7-segment display.'],
    ['470Ω', '10+', 1, 'Dimmer LEDs, optocoupler inputs, WS2812B data lines, and LED current limits on 9V.'],
    ['680Ω', '10+', 2, 'LED resistor on 9–12V supplies, and a medium current limit.'],
    ['1kΩ', '10+', 1, 'One of the most-used values: transistor base resistor, LED on 12V, signal protection, and the top half of a 5V → 3.3V divider (with 2.2kΩ).'],
    ['2.2kΩ', '10+', 1, 'Bottom half of the 1k/2.2k divider that brings a 5V signal (like the HC-SR04 echo) down to 3.3V; also base resistors and I2C pull-ups.'],
    ['4.7kΩ', '10+', 1, 'The standard pull-up resistor for I2C lines and the DS18B20 1-Wire data line.'],
    ['10kΩ', '20+', 1, 'The most common value of all: button pull-ups and pull-downs, LDR and thermistor dividers, 555 timing, and MOSFET gate pull-downs.'],
    ['22kΩ', '10+', 2, 'Higher-value dividers, timing circuits and op-amp gain setting.'],
    ['47kΩ', '10+', 2, '555 and RC timing, and dividers that draw very little current.'],
    ['100kΩ', '10+', 1, 'Weak pull-downs on transistor bases and MOSFET gates, battery-voltage dividers that waste little power, and long timers.'],
    ['220kΩ', '10+', 2, 'Op-amp feedback for high gain, and very low-current dividers.'],
    ['470kΩ', '10+', 2, 'High-value timing and bias resistors.'],
    ['1MΩ', '10+', 2, 'Very high impedance: long RC delays, touch inputs and op-amp bias networks.'],
  ] },

{ n:4, title:'Potentiometers & variable resistors', intro:'Adjustable and sensing resistors.',
  notes:[['tip', 'These are very useful for learning voltage dividers and analog input.']],
  items:[
    ['10kΩ potentiometer', '5', 1, 'The standard pot: an adjustable voltage divider for analog input (analogRead), dimmers, and setting comparator thresholds.'],
    ['100kΩ potentiometer', '3', 2, 'Wide-range timing adjustment on 555 circuits, and high-impedance dividers.'],
    ['1kΩ potentiometer', '2', 2, 'Low-value adjustment where more current flows, such as trimming LED brightness.'],
    ['10kΩ trimpot', '5', 2, 'Small screwdriver-set pots you adjust once and leave: LCD contrast, comparator thresholds and calibration.'],
    ['LDR / photoresistor', '5', 1, 'Resistance falls as light increases. Used in night lights, light alarms and light meters — always as part of a voltage divider.'],
    ['Thermistor, NTC 10kΩ', '5', 2, 'Resistance falls as temperature rises. Temperature sensing, over-heat alarms and thermostats.'],
    ['Thermistor assortment', '1', 6, 'Different values and PTC types to compare their curves, including PTC resettable fuses for circuit protection.'],
  ] },

{ n:5, title:'Capacitors', intro:'Get an assortment rather than individual pieces — and several of each value.',
  notes:[['tip', 'Electrolytic capacitors are polarised: the stripe marks the negative leg. Always use one rated above your circuit’s voltage.']],
  groups:[
    { title:'Ceramic capacitors', items:[
      ['100pF', 'Several', 2, 'High-frequency filtering and stabilising oscillators and op-amps.'],
      ['1nF (code 102)', 'Several', 2, 'Filtering noise on signal lines, and timing in fast oscillators.'],
      ['10nF (code 103)', 'Several', 2, 'Decoupling the 555’s CTRL pin (pin 5), and high-frequency timing.'],
      ['100nF (code 104)', 'Several', 1, 'The decoupling capacitor: one right next to every IC’s power pins to swallow noise spikes. You will use more of these than any other capacitor.'],
      ['1µF ceramic', 'Several', 2, 'Stability capacitor on regulator inputs and outputs, and filtering for sensors and ADC inputs.'],
    ] },
    { title:'Electrolytic capacitors', items:[
      ['1µF electrolytic', 'Several', 2, 'Timing and coupling at small values; fast 555 oscillators.'],
      ['10µF', 'Several', 1, 'Regulator input and output capacitors, 555 blinkers (about 1Hz), audio coupling and local power smoothing.'],
      ['47µF', 'Several', 2, 'Smoothing module and motor-driver supplies, and slower timing.'],
      ['100µF', 'Several', 1, 'Bulk decoupling on breadboard power rails, next to servos and motor drivers, and longer RC delays.'],
      ['220µF', 'Several', 2, 'Smoothing supplies with bigger loads, and audio amplifier outputs.'],
      ['470µF', 'Several', 2, 'Reservoir capacitor for motors and LED strips; capacitor fade-out exercises.'],
      ['1000µF', 'Several', 3, 'Big reservoir across WS2812B LED strips and motor supplies to absorb current surges; long delays.'],
    ] },
    { title:'Also buy extra', note:'These are used constantly for decoupling and power filtering.', items:[
      ['100nF ceramic', '10', 1, 'Enough to decouple every IC on several breadboards at once.'],
      ['10µF electrolytic', '10', 1, 'One for every regulator and module supply you build.'],
      ['100µF electrolytic', '10', 2, 'Bulk smoothing on each breadboard rail and next to every motor or servo.'],
    ] },
  ] },

{ n:6, title:'LEDs', intro:'Buy an assortment — you will use LEDs in almost every early circuit.',
  items:[
    ['Red 5mm LED', '10', 1, 'The most common indicator, with the lowest forward voltage (about 2V), so it works almost anywhere: power and status lights, alarms.'],
    ['Green 5mm LED', '10', 1, '“OK / ready” indicators and traffic-light projects.'],
    ['Blue 5mm LED', '10', 1, 'Higher forward voltage (about 3V) — it shows why the resistor value depends on the colour. Status and decorative lighting.'],
    ['Yellow 5mm LED', '10', 1, 'Warning indicators and traffic-light projects.'],
    ['White 5mm LED', '10', 1, 'Illumination, night lights and torches (about 3V forward voltage).'],
    ['RGB LED', '5', 1, 'Three LEDs in one package — any colour by mixing. Status colours, mood lights and PWM practice.'],
    ['3mm LEDs', '10', 2, 'Smaller indicators for compact builds and LED bar graphs.'],
    ['High-brightness LEDs', '5', 3, 'Very bright for torches, lighting and indicators visible outdoors. Drive them through a transistor at higher currents.'],
  ],
  groups:[
    { title:'Also get', items:[
      ['LED holder assortment', 'If available', 6, 'Clips that mount LEDs neatly in panel holes for finished enclosures.'],
      ['Diffused LEDs', 'Some', 2, 'A frosted lens spreads the light evenly — easier on the eyes than water-clear LEDs for indicators.'],
      ['Common-anode RGB LEDs', 'Some', 2, 'The shared pin goes to +5V and each colour lights when its pin goes LOW. Having both types teaches you the difference.'],
      ['Common-cathode RGB LEDs', 'Some', 2, 'The shared pin goes to GND and each colour lights with a HIGH or PWM signal — the easier type to start with.'],
    ] },
  ] },

{ n:7, title:'Diodes', intro:'Very important for electronics and motor circuits.',
  items:[
    ['1N4148 signal diode', '10', 2, 'Fast small-signal diode: logic steering, protection clamps on inputs, the 555 duty-cycle trick and diode-OR circuits.'],
    ['1N4007 rectifier diode', '20', 2, '1A rectifier for power circuits: reverse-polarity protection, and the flyback diode across relay coils and motors.'],
    ['1N5819 Schottky diode', '10', 3, 'Low voltage drop (about 0.3V): efficient reverse-polarity protection and combining supplies, e.g. USB and battery.'],
    ['5.1V Zener diode', '5', 2, 'A simple 5V reference and clamp — protects a 5V input from over-voltage, and makes battery-level indicators.'],
    ['12V Zener diode', '5', 3, 'Clamps voltage spikes on 12V lines and protects MOSFET gates.'],
    ['Bridge rectifier', '5', 6, 'Four diodes in one package that turn AC into DC — for understanding power supplies, and accepting power of either polarity.'],
  ] },

{ n:8, title:'Transistors', intro:'Get around 5–10 pieces of each.',
  groups:[
    { title:'NPN', items:[
      ['BC547', '5–10', 2, 'General-purpose small NPN (100mA): switching LEDs, buzzers and small relays, and simple amplifiers. Used in most transistor exercises.'],
      ['2N2222', '5–10', 2, 'Handles up to about 600mA — switching relay coils and small motors. Its pin order (E-B-C) is the reverse of the BC547.'],
      ['2N3904', '5–10', 2, 'The small-signal NPN found in countless schematics and tutorials; interchangeable with the BC547 for most learning.'],
    ] },
    { title:'PNP', items:[
      ['BC557', '5–10', 2, 'The PNP partner of the BC547, for high-side switching — switching the positive side of a load.'],
      ['2N3906', '5–10', 2, 'The PNP partner of the 2N3904.'],
    ] },
    { title:'Power transistors', note:'These help you learn about controlling higher-current loads.', items:[
      ['TIP120', '2–3', 3, 'NPN Darlington (5A): drives motors, solenoids and LED strips from an Arduino pin. It drops 1–2V, so it runs warm.'],
      ['TIP122', '2–3', 3, 'The 100V version of the TIP120, for higher-voltage loads.'],
      ['TIP41', '2–3', 5, 'NPN power transistor (6A) for heavier loads and linear power stages.'],
      ['TIP42', '2–3', 5, 'The PNP partner of the TIP41 — for H-bridges and high-side power switching.'],
    ] },
  ] },

{ n:9, title:'MOSFETs', intro:'Very useful once you start controlling motors, LEDs, pumps and fans.',
  notes:[['tip', 'Prefer logic-level MOSFETs, especially ones that switch fully from 3.3V GPIO.']],
  items:[
    ['IRLZ44N', '3–5', 3, 'Logic-level N-channel MOSFET rated for tens of amps: switches motors, LED strips, pumps and heaters directly from an Arduino, with little heat.'],
    ['IRF520', '2–3', 6, 'Used on many cheap “MOSFET modules”, but not logic-level — it barely turns on from 3.3V or 5V. Good for learning why the gate threshold matters; use the IRLZ44N for real loads.'],
    ['AO3400', '5–10', 4, 'Tiny SMD logic-level MOSFET that switches fully from 3.3V — ideal for ESP32 projects on your own boards (needs an adapter board to breadboard).'],
  ] },

{ n:10, title:'ICs — beginner collection', intro:'Chips that do a job for you — most in DIP packages that fit a breadboard.',
  notes:[['tip', 'The driver ICs aren’t the best modern motor drivers, but they are very useful for learning.']],
  groups:[
    { title:'Timer', items:[
      ['NE555', '5', 2, 'Timer IC for blinkers, tone generators, one-shot timers and PWM — dozens of circuits without any code.'],
    ] },
    { title:'Logic', items:[
      ['74HC00', '2–3', 2, 'Four NAND gates — the “universal” gate; any logic can be built from it.'],
      ['74HC02', '2–3', 2, 'Four NOR gates (note its different pinout). Also used to build simple latches.'],
      ['74HC04', '2–3', 2, 'Six inverters (NOT gates): flip signals, buffer them, or build simple oscillators.'],
      ['74HC08', '2–3', 2, 'Four AND gates: “only when both are true” logic.'],
      ['74HC32', '2–3', 2, 'Four OR gates: “when either is true” logic.'],
      ['74HC86', '2–3', 2, 'Four XOR gates: half adders, parity checks and toggling a signal.'],
    ] },
    { title:'Op-amps', items:[
      ['LM358', '5', 2, 'Dual op-amp that runs from a single 5V supply: comparators, sensor amplifiers and buffers.'],
      ['LM324', '2', 3, 'Four op-amps in one chip — multi-channel sensor conditioning and filters.'],
    ] },
    { title:'Voltage regulators', items:[
      ['LM7805', '2–3', 2, 'Fixed 5V regulator (7–35V in): a stable 5V supply from 9V or 12V.'],
      ['LM7812', '2', 3, 'Fixed 12V regulator for 12V motors, relays and fans from a higher supply.'],
      ['LM317', '2', 3, 'Adjustable regulator (1.25–37V) set by two resistors — your own variable supply, 3.3V rails, or constant-current LED drivers.'],
    ] },
    { title:'Driver ICs', items:[
      ['ULN2003', '2', 3, 'Seven Darlington drivers with built-in diodes: steppers (28BYJ-48), relays and solenoids from logic pins.'],
      ['L293D', '2', 3, 'Dual H-bridge (600mA) with built-in diodes: forward and reverse control of two small DC motors — great for learning H-bridges.'],
    ] },
  ] },

{ n:11, title:'Switches & buttons', intro:'Every way of giving your circuit an input.',
  items:[
    ['Push buttons', '20', 1, 'Momentary inputs for everything: triggers, menus, counters and games.'],
    ['Toggle switches', '5', 2, 'Latching on/off with a lever — power switches and mode selectors.'],
    ['Slide switches', '5', 2, 'Compact switches that fit a breadboard — power switches for battery projects and option selectors.'],
    ['Rocker switches', '5', 6, 'Panel-mount power switches for finished enclosures and higher currents.'],
    ['DIP switches', '2', 2, 'A row of tiny switches: binary input, configuration settings and addresses.'],
    ['Push-button caps', '10', 2, 'Coloured caps for 12×12mm tactile buttons — easier to press, and you can colour-code them (green = start).'],
    ['Rotary encoder', '3', 3, 'An endless knob with clicks and a push switch — menus, volume and setting values on displays.'],
  ] },

{ n:12, title:'Relays', intro:'Let a small signal switch a separate, bigger circuit.',
  notes:[['key', 'For your early experiments, use relay modules rather than driving relay coils directly from GPIO — and stick to low-voltage loads while learning.']],
  items:[
    ['5V relay', '5', 3, 'Bare relays for learning the coil and contacts (COM, NO, NC), and why a transistor and flyback diode are needed.'],
    ['12V relay', '2', 5, 'For 12V systems — car electronics, 12V pumps and fans — where the coil runs from the main supply.'],
    ['1-channel relay module', '2', 3, 'Relay with its transistor, diode and LED already on board: switch a lamp, pump or fan from one GPIO pin.'],
    ['4-channel relay module', '1', 4, 'Four independent loads — home-automation and irrigation projects.'],
  ] },

{ n:13, title:'Displays', intro:'Start with these.',
  items:[
    ['16×2 LCD', '1', 3, 'Bare character LCD with a parallel interface — learn how the 4-bit interface works with the LiquidCrystal library.'],
    ['16×2 I2C LCD', '1', 3, 'The same LCD with an I2C backpack: only 4 wires. Menus, readouts and status screens.'],
    ['20×4 LCD', '1', 4, 'Four lines of 20 characters — dashboards showing several readings at once.'],
    ['0.96″ OLED (I2C)', '2', 3, 'Sharp 128×64 graphics display: sensor dashboards, icons and small graphs on the device itself.'],
    ['1.3″ OLED', '1', 4, 'A larger OLED, usually with the SH1106 driver — choose the matching library.'],
    ['7-segment display, single digit', '4', 2, 'Learn how segments are driven — counters and dice, even without a microcontroller.'],
    ['4-digit 7-segment display', '2', 3, 'Clocks, timers and numeric readouts, multiplexed or with a TM1637 driver.'],
    ['MAX7219 8×8 LED matrix', '1', 3, 'A driver and matrix together: scrolling text and simple animations from three pins.'],
  ] },

{ n:14, title:'Sensors — basic', intro:'This is where your IoT learning becomes much more interesting.',
  items:[
    ['LDR', '5', 1, 'Light level: night lights, light alarms and day/night detection.'],
    ['DHT11', '2', 3, 'Cheap temperature and humidity (±2°C, ±5%): your first humidity readings.'],
    ['DHT22', '1', 3, 'More accurate temperature and humidity (±0.5°C) for weather stations and room monitors.'],
    ['DS18B20', '2', 3, 'Digital 1-Wire temperature sensor, also as a waterproof probe: liquids, soil, and several sensors on one wire.'],
    ['HC-SR04 ultrasonic', '2', 3, 'Distance from 2cm to 4m by echo: obstacle avoidance, parking sensors and tank levels. Its 5V echo needs a divider on an ESP32.'],
    ['PIR motion sensor HC-SR501', '2', 3, 'Detects moving people: motion lights, alarms and occupancy.'],
    ['IR obstacle sensor', '2', 3, 'Short-range (2–30cm) object detection with an adjustable threshold: robot cars and object counting.'],
    ['IR receiver', '2', 3, 'Decodes TV-remote signals (38kHz) so you can control your projects with any remote.'],
    ['IR transmitter (IR LED)', '5', 3, 'Sends infrared: control a TV or air conditioner, or make beam-break sensors with a receiver.'],
    ['Sound sensor', '2', 3, 'Microphone plus comparator: clap switches and noise detection (not for recording audio).'],
    ['Vibration sensor', '2', 3, 'Detects shaking and knocks (e.g. SW-420): anti-theft alarms and machine monitoring.'],
    ['Flame sensor', '1', 3, 'Infrared flame detection within about 1m — fire-fighting robot demos, not a safety device.'],
    ['Rain sensor', '1', 4, 'Detects rain on a sensing board: weather stations, closing windows, pausing irrigation.'],
    ['Soil moisture sensor', '2', 4, 'Plant monitoring and smart irrigation. Capacitive types last much longer than resistive ones.'],
    ['MQ-2 gas sensor', '1', 6, 'Smoke and combustible gases. Needs heater power and warm-up time — for demos and trends, not precise readings.'],
    ['MQ-135 air-quality sensor', '1', 6, 'General air-quality trend (ammonia, NOx, smoke) — not a true CO₂ meter.'],
  ] },

{ n:15, title:'Sensors — more useful IoT sensors', intro:'Once you move beyond the absolute beginner level.',
  notes:[['tip', 'These are especially useful later for your autonomous and robot projects.']],
  items:[
    ['MPU6050', '1–2', 5, 'Accelerometer + gyroscope: tilt, self-balancing robots, RC car motion and crash detection.'],
    ['MPU9250', '1', 5, 'A 9-axis IMU with a magnetometer for heading — drones and orientation. Many modules sold today are clones.'],
    ['BMP280', '1–2', 4, 'Pressure + temperature: barometer, altitude and weather trends.'],
    ['BME280', '1–2', 4, 'Pressure + humidity + temperature in one chip: complete weather stations.'],
    ['BH1750', '1–2', 4, 'Calibrated light intensity in lux: smart lighting and plant light monitoring.'],
    ['VL53L0X', '1–2', 5, 'Laser time-of-flight distance (up to about 2m) with a narrow beam: precise robot sensing.'],
    ['TCS34725', '1', 5, 'Colour sensor (red, green, blue and clear): colour sorting, colour-line following and colour matching.'],
    ['HX711', '1', 5, '24-bit amplifier for load cells: digital scales, weighing and force measurement.'],
    ['MAX30102', '1', 5, 'Optical heart-rate and blood-oxygen sensor: pulse-monitoring projects (not medical grade).'],
    ['INA219', '1–2', 4, 'Voltage, current and power over I2C: battery and solar monitoring, and measuring how much your project draws.'],
  ] },

{ n:16, title:'Temperature & environmental', intro:'A ladder of temperature sensors, each teaching a new way of reading data.',
  flow:['Analog sensors', 'Digital sensors', 'I2C', '1-Wire', 'Calibrated sensor modules'],
  flowLabel:'You’ll learn the difference between',
  items:[
    ['DHT11', '2', 3, 'A digital sensor with its own single-wire timing protocol — your first sensor that talks in pulses instead of voltages. (Also in section 14.)'],
    ['DHT22', '1', 3, 'The more accurate DHT, for when the DHT11’s ±2°C is not good enough. (Also in section 14.)'],
    ['DS18B20', '2', 3, 'The 1-Wire bus: many sensors share one data wire, each with its own address. (Also in section 14.)'],
    ['LM35', '2', 3, 'Analog: 10mV per °C, read directly with analogRead() — the simplest precise sensor and the first step on the ladder.'],
    ['BMP280', '1–2', 4, 'An I2C, factory-calibrated module — pressure and temperature as ready-made numbers. (Also in section 15.)'],
    ['BME280', '1–2', 4, 'The top of the ladder: calibrated temperature, humidity and pressure over I2C. (Also in section 15.)'],
  ] },

{ n:17, title:'Motors & motion', intro:'You will definitely need these eventually.',
  items:[
    ['SG90 servo', '3', 3, 'Small 180° servo: steering, sensor turrets, small robot arms and latches.'],
    ['MG90S metal-gear servo', '2', 5, 'The same size as the SG90 but with metal gears that survive crashes — RC car steering.'],
    ['MG996R servo', '1', 5, 'A strong standard servo (about 10kg·cm): robot arms and heavier mechanisms. Needs its own power supply.'],
    ['3–6V DC motor', '3', 2, 'The basic motor for learning transistor and MOSFET switching, PWM speed control and flyback diodes.'],
    ['Geared DC motor', '2', 5, 'Slow, strong motors (TT type) that drive robot-car wheels.'],
    ['N20 gear motor', '2', 5, 'Tiny metal-gear motors, often with encoders — compact robots and precise movement.'],
    ['28BYJ-48 stepper motor', '2', 3, 'A geared stepper for exact positioning: dials, blinds and rotating displays.'],
    ['ULN2003 driver board', '2', 3, 'The driver board that goes with the 28BYJ-48 stepper.'],
    ['Small vibration motor', '2', 3, 'Haptic feedback and silent alerts, driven through a transistor.'],
    ['Small DC fan', '2', 4, 'Cooling for projects and thermostat demos, switched by a MOSFET or relay.'],
  ] },

{ n:18, title:'Motor drivers', intro:'Boards that let a microcontroller run motors safely.',
  notes:[['key', 'For your future RC car, the TB6612FNG and DRV8833 are much more useful than relying on the L298N.']],
  items:[
    ['L298N', '1', 3, 'The classic dual H-bridge, up to 2A — easy to start with, but it wastes about 2V and runs hot.'],
    ['TB6612FNG', '2', 5, 'Efficient MOSFET dual H-bridge (1.2A per channel) that accepts 3.3V logic — the best choice for your RC car’s TT motors.'],
    ['DRV8833', '1', 5, 'A tiny, efficient dual H-bridge for low-voltage battery robots (2.7–10.8V).'],
    ['A4988', '1', 6, 'Stepper-motor driver for NEMA 17 motors — 3D printers, plotters and CNC machines.'],
  ] },

{ n:19, title:'Arduino / microcontrollers', intro:'You already have an Arduino UNO — keep it for learning. But buy these.',
  flow:['Arduino UNO', 'Arduino Nano', 'ESP32', 'ESP32-S3', 'IoT / Wi-Fi / Bluetooth', 'Robotics'],
  flowLabel:'Your main learning path',
  items:[
    ['Arduino UNO compatible', '1', 3, 'A second UNO, so one can stay wired into a project while you keep learning on the other.'],
    ['Arduino Nano', '2', 3, 'An UNO in a small breadboard-friendly package — permanent and compact builds.'],
    ['ESP32 DevKit', '2', 4, 'Wi-Fi, Bluetooth and a fast processor at 3.3V: the main board for IoT. Two let you build a sender and a receiver (ESP-NOW, remote plus car).'],
    ['ESP32-S3 development board', '1', 5, 'A faster ESP32 with native USB and AI instructions — camera, display and voice projects.'],
    ['ESP8266 NodeMCU', '1', 4, 'The older, cheaper Wi-Fi board — fine for simple connected sensors, but the ESP32 is the better main choice.'],
    ['Raspberry Pi Pico / Pico W', '1', 4, 'RP2040 board for MicroPython and precise timing (PIO); the W version adds Wi-Fi.'],
  ] },

{ n:20, title:'Communication modules', intro:'Buy later, but they are worth having in the kit.',
  notes:[['key', 'For your eventual RC and IoT work, the ESP32’s own Wi-Fi and Bluetooth should be your main focus.']],
  items:[
    ['HC-05 Bluetooth', '1', 4, 'Classic Bluetooth serial module (can be master or slave): a wireless serial link to a phone app or another HC-05.'],
    ['HC-06 Bluetooth', '1', 4, 'Slave-only Bluetooth serial — the simplest phone-to-Arduino control.'],
    ['NRF24L01', '2', 5, '2.4GHz radios used in pairs: low-latency remote controls and sensor networks between boards. Needs a clean 3.3V supply with a capacitor.'],
    ['LoRa SX1278', '2', 5, 'Long-range (kilometres), low-data radio: remote sensors, farm and tank monitoring. Check which frequency band is allowed where you live.'],
    ['RFID RC522', '1', 4, '13.56MHz card reader: door locks, attendance and arming alarms.'],
    ['GPS NEO-6M', '1', 5, 'Position, speed and time over UART: trackers and outdoor robots.'],
    ['ESP32 (Wi-Fi + Bluetooth)', '2', 4, 'Built-in Wi-Fi and Bluetooth — for most projects the ESP32 replaces separate Bluetooth and Wi-Fi modules.'],
  ] },

{ n:21, title:'Real-time clock & memory', intro:'Keep time and store data.',
  items:[
    ['DS3231 RTC', '1', 4, 'An accurate real-time clock with battery backup: timestamps, alarms and schedules even without Wi-Fi.'],
    ['MicroSD card module', '1', 4, 'Log data to files (CSV): weather history, GPS tracks and sensor logs.'],
    ['8GB / 16GB microSD card', '1–2', 4, 'Storage for data loggers, audio files for players, and general use.'],
    ['EEPROM module', '1', 4, 'Small I2C memory (e.g. AT24C256) that keeps settings and counters through power loss.'],
  ] },

{ n:22, title:'Power supplies', intro:'An important category — don’t skip it.',
  notes:[['key', 'Eventually buy a DC bench power supply, preferably 0–30V with current limiting. It will become one of your most useful pieces of equipment.']],
  items:[
    ['5V 2A adapter', '1', 1, 'Clean 5V for Arduino and ESP32 boards, small servos and short LED strips.'],
    ['5V 3A adapter', '1', 4, 'More current for several servos, LED strips and Raspberry Pi-class loads.'],
    ['9V adapter', '1', 1, 'Input for the breadboard power module and the Arduino barrel jack; also for regulator exercises.'],
    ['12V 2A adapter', '1', 3, '12V motors, fans, pumps, LED strips and relays, and the input for buck-converter exercises.'],
    ['DC barrel connectors', '1 set', 2, 'Male and female 5.5×2.1mm plugs with screw terminals — connect adapters to breadboards and projects without cutting cables.'],
    ['DC splitter cables', '1–2', 4, 'Power two devices, such as a board and a motor driver, from one adapter.'],
    ['DC jack terminals', '1 set', 2, 'Panel and PCB jacks for adding a power input to your own builds.'],
    ['Adjustable supply', '1', 3, 'A variable-voltage source (for example an LM2596 module on a 12V adapter) to see how circuits behave at different voltages.'],
    ['DC bench power supply, 0–30V with current limiting', '1', 6, 'Set a voltage and a current limit, so a short circuit becomes harmless instead of smoke. One of the most useful instruments you will own.'],
  ] },

{ n:23, title:'Batteries', intro:'For experimenting away from the mains adapter.',
  notes:[['warn', 'For lithium batteries, use proper protected cells and holders and a suitable charger or BMS.'], ['warn', 'Do not connect a bare 18650 directly to an ESP32 — a full cell is 4.2V. Use a regulator.']],
  items:[
    ['AA rechargeable batteries', '4–8', 2, 'NiMH 1.2V cells for portable circuits and small motors — cheaper than alkaline in the long run.'],
    ['AA battery holder', '2', 2, '2×AA (about 2.4–3V) or 4×AA (about 4.8–6V) packs for portable circuits and motors.'],
    ['AAA rechargeable batteries', '4', 4, 'Smaller cells for compact remotes and wearables.'],
    ['AAA battery holder', '2', 4, 'Holders for AAA packs.'],
    ['9V battery', '2', 1, 'Quick portable power for regulator and Zener exercises and small circuits — low capacity, so not for motors.'],
    ['9V battery clip', '2', 1, 'A snap connector with leads for 9V batteries.'],
    ['18650 protected cells', '2–4', 5, '3.7V lithium cells (2000–3500mAh) with a built-in protection circuit: ESP32 projects and robot cars (two in series = 7.4V).'],
    ['18650 holder', '2', 5, 'Holds the cells safely with proper contacts — never solder directly to a cell.'],
    ['18650 charger', '1', 5, 'A proper lithium charger (constant current, then constant voltage) to charge cells safely outside the project.'],
  ] },

{ n:24, title:'Power-management modules', intro:'Small boards that convert and manage power.',
  notes:[['tip', 'These will teach you a huge amount about real-world power systems.']],
  items:[
    ['LM2596 buck converter', '2', 4, 'Steps voltage down efficiently (up to about 3A): 12V or 7.4V → 5V for ESP32s, servos and Raspberry Pis. Set the output with its trimpot before connecting a load.'],
    ['MT3608 boost converter', '2', 4, 'Steps voltage up: a 3.7V lithium cell → 5V or 12V for small loads.'],
    ['5V regulator module', '2', 3, 'Ready-made regulated 5V for sensors and modules.'],
    ['3.3V regulator module', '2', 4, 'Clean 3.3V (e.g. AMS1117-3.3) for ESP modules, the NRF24L01 and 3.3V sensors.'],
    ['TP4056 protected charging module', '2', 5, 'Charges a single lithium cell from USB. Buy the version with the protection chip (DW01).'],
    ['USB-to-5V power module', '1', 3, 'Brings USB power onto a breadboard — run circuits from a phone charger or power bank.'],
  ] },

{ n:25, title:'Connectors', intro:'Don’t underestimate these little things.',
  notes:[['tip', 'Also get a JST / Dupont crimping tool if you plan to build your own wiring.']],
  items:[
    ['JST-XH', 'Assorted', 5, '2.5mm-pitch connectors used on battery balance leads and many modules.'],
    ['JST-PH', 'Assorted', 5, '2.0mm-pitch connectors for small LiPo batteries and compact sensor boards.'],
    ['Dupont connectors', 'Assorted', 3, 'The standard 2.54mm header connectors — build custom jumper cables to exact length.'],
    ['KF301 screw terminals', 'Assorted', 3, 'PCB screw terminals (5.08mm) for power and motor wires on perfboard.'],
    ['DC barrel connectors', 'Assorted', 2, 'Power inputs for projects (see power supplies).'],
    ['XT30', 'Assorted', 5, 'A small high-current battery connector (up to about 30A): RC car battery packs.'],
    ['XT60', 'Assorted', 5, 'A larger high-current connector (up to about 60A): big batteries and motor controllers.'],
    ['2-pin connectors', 'Assorted', 3, 'Power leads, buzzers and single loads.'],
    ['3-pin connectors', 'Assorted', 3, 'Servos and three-wire sensors (power, ground, signal).'],
    ['4-pin connectors', 'Assorted', 3, 'I2C devices and stepper motors.'],
    ['5-pin connectors', 'Assorted', 4, 'UART with control lines, and five-wire unipolar steppers like the 28BYJ-48.'],
    ['JST / Dupont crimping tool', '1', 5, 'Crimps metal pins onto wires so you can make neat, reliable custom cables.'],
  ] },

{ n:26, title:'Modules for future IoT projects', intro:'A useful assortment of plug-in modules.',
  items:[
    ['Buzzer module', '1–2', 3, 'A buzzer with its driver transistor on a 3-pin board — loud alerts from one GPIO pin.'],
    ['Active buzzer', '2–3', 1, 'Beeps on plain DC: alarms and doorbells.'],
    ['Passive buzzer', '2–3', 2, 'Plays tones and melodies from a changing signal (tone()).'],
    ['RGB LED module', '1–2', 3, 'An RGB LED with its resistors on board — a plug-and-play colour indicator.'],
    ['Relay module', '1–2', 3, 'Switch a separate load from one pin (see section 12).'],
    ['Joystick module', '1–2', 3, 'Two pots and a button: control servos, robot cars and games.'],
    ['Rotary encoder module', '1–2', 3, 'An encoder with pull-up resistors on board: menus and settings.'],
    ['Keypad 4×4', '1', 3, '16 keys scanned by rows and columns: codes, calculators and menus.'],
    ['Keypad 4×3', '1', 3, 'A phone-style 12-key pad: PIN entry and door locks.'],
    ['IR remote + receiver', '1 set', 3, 'A complete remote-control kit: control your projects from across the room.'],
    ['Laser diode module', '1', 3, 'A low-power red laser: beam-break alarms and pointers. Never look into the beam.'],
    ['Microphone module', '1', 4, 'Analog audio (e.g. MAX9814) for sound levels and simple audio projects.'],
    ['Sound detection module', '1', 3, 'A digital “loud sound” trigger with an adjustable threshold: clap switches.'],
    ['Touch sensor TTP223', '2–3', 3, 'A single capacitive touch pad: replace buttons, or hide a switch behind plastic.'],
    ['Capacitive touch module', '1', 4, 'Multi-channel touch (e.g. MPR121): touch keypads and fruit pianos.'],
    ['Hall-effect sensor', '2–3', 3, 'Detects magnets: wheel speed, RPM and door position.'],
    ['Reed switch', '2–3', 2, 'A magnet-operated switch that needs no power: doors, windows and float switches.'],
    ['Tilt sensor', '2', 3, 'A ball switch that closes when tipped: tilt alarms and orientation toggles.'],
  ] },

{ n:27, title:'RFID / NFC', intro:'Identification by tapping a card or tag.',
  items:[
    ['RC522 RFID module', '1', 4, 'A 13.56MHz reader and writer (SPI, 3.3V): access control, attendance and arming alarms.'],
    ['RFID cards', '5', 4, 'MIFARE cards to program and test with.'],
    ['RFID key fobs', '5', 4, 'Key-ring tags with the same chips as the cards — for door-lock projects.'],
    ['PN532 NFC module', '1', 6, 'Later: a full NFC controller that can talk to phones and NTAG stickers.'],
  ] },

{ n:28, title:'Storage & organisation', intro:'This sounds boring — but after 300 resistors become one mysterious pile, you’ll care.',
  notes:[['key', 'Label everything.']],
  items:[
    ['Component organiser box', '1–2', 1, 'Adjustable compartments for resistors, LEDs and capacitors, one value per compartment.'],
    ['Small screw boxes', '2', 2, 'Screws, nuts, standoffs and spacers.'],
    ['IC storage box', '1', 2, 'Anti-static foam or tubes that keep IC legs straight and chips safe.'],
    ['Wire organiser', '1', 2, 'Holds hookup-wire spools so colours don’t tangle.'],
    ['Breadboard storage case', '1', 3, 'Keeps a built circuit intact between sessions.'],
    ['Label stickers', '1 set', 1, 'Label every compartment with its value.'],
    ['Permanent marker', '1', 1, 'Mark values on bags, cable ends and module I2C addresses.'],
    ['Small zip-lock bags', '1 pack', 1, 'Keep the parts for each project together.'],
  ] },

{ n:29, title:'Safety equipment', intro:'Don’t skip this.',
  notes:[['warn', 'Don’t experiment with damaged or swollen lithium cells.']],
  items:[
    ['Safety glasses', '1', 1, 'Clipped legs fly, solder spits and capacitors can burst. Wear them when cutting and soldering.'],
    ['Heat-resistant soldering mat', '1', 3, 'A silicone mat that protects the bench and holds small parts while you solder.'],
    ['Heat-resistant gloves', '1 pair', 5, 'For handling hot parts and heat-gun work.'],
    ['Fume extractor', '1', 3, 'A fan and filter that pulls solder-flux fumes away from your face.'],
    ['Small fire extinguisher', '1', 5, 'Lithium batteries and power circuits can catch fire — keep a suitable extinguisher near the bench.'],
    ['Insulated test leads', '1 set', 1, 'Probes rated for your meter’s voltage and current, for safe measurements.'],
    ['Insulated screwdriver set', '1 set', 5, 'For working near higher voltages and live terminals.'],
  ] },

{ n:30, title:'Tools you’ll want later', intro:'Not necessary on day 1, but add them to your roadmap.',
  items:[
    ['Oscilloscope (2-channel digital)', '1', 6, 'Shows voltage over time: PWM, noise, 555 waveforms and serial signals. Extremely useful once you understand basic voltage and current.'],
    ['Logic analyser (8-channel USB)', '1', 6, 'Records digital signals and decodes I2C, SPI, UART and PWM on your PC — see exactly why a module won’t talk.'],
    ['Function generator', '1', 6, 'Produces sine, square and triangle signals for studying frequency, AC signals, filters and amplifiers.'],
  ] },
];

/* 31. The recommended “buy now” list: the first purchase, if you don't want 200 things at once. */
const KIT_BUY_NOW = [
  { group:'Tools', items:['Digital multimeter', 'Wire stripper', 'Side cutter', 'Long-nose pliers', 'Screwdriver set', 'Soldering iron', 'Solder', 'Desoldering pump', 'Heat-shrink tubing'] },
  { group:'Prototyping', items:['2 × full-size breadboard', '2 × mini breadboard', 'M-M jumper wires', 'M-F jumper wires', 'F-F jumper wires', 'Solid-core wire', 'Breadboard power module'] },
  { group:'Components', items:['Resistor assortment', 'Capacitor assortment', 'LED assortment', 'Diode assortment', 'NPN/PNP transistor assortment', 'MOSFET assortment', 'Potentiometer assortment', 'Push buttons', 'Switches', 'Buzzers', 'LDR', 'Thermistors', 'Relay'] },
  { group:'ICs', items:['NE555', 'LM358', 'LM324', '74HC00', '74HC04', '74HC08', 'ULN2003', 'L293D'] },
  { group:'Sensors', items:['HC-SR04', 'PIR', 'DHT11', 'DHT22', 'DS18B20', 'LDR', 'Soil moisture', 'IR obstacle', 'MPU6050', 'BMP280', 'BME280', 'BH1750'] },
  { group:'Controllers', items:['Arduino Nano', '2 × ESP32 DevKit', 'Raspberry Pi Pico W'] },
  { group:'Motors', items:['SG90 servo ×3', 'DC motors ×3', 'N20 gear motors ×2', '28BYJ-48 stepper ×2', 'TB6612FNG', 'DRV8833', 'L298N'] },
  { group:'Power', items:['AA rechargeable batteries', 'AA holders', '9V batteries', '18650 protected cells', '18650 holders', 'Proper 18650 charger', '5V adapter', '12V adapter', 'LM2596', 'MT3608', 'TP4056'] },
  { group:'Displays', items:['16×2 LCD', 'I2C LCD', '0.96″ OLED', '7-segment display', 'MAX7219 matrix'] },
];

/* The learning progression the kit supports, top to bottom. */
const KIT_PATH = [
  { title:'Electronics', branches:[
    { title:'Fundamentals', items:['Voltage / current', 'Resistance', 'Ohm’s law', 'Series / parallel'] },
    { title:'Tools', items:['Multimeter', 'Soldering', 'Power supply', 'Oscilloscope'] },
  ] },
  { title:'Basic circuits', chains:[['LED', 'Button', 'Buzzer'], ['Resistor', 'Capacitor'], ['Diode', 'Transistor', 'MOSFET'], ['ICs']] },
  { title:'Arduino UNO', items:['Sensors', 'Displays', 'Motors', 'Relays'] },
  { title:'ESP32', items:['Wi-Fi', 'Bluetooth', 'MQTT'] },
  { title:'IoT' },
  { title:'Robotics / RC car', chains:[['ESP32 + sensors + motors', 'Camera + telemetry', 'Autonomous systems']] },
];

const KIT_CLOSING = 'Don’t buy every advanced sensor or module immediately. Buy the core kit first, then add modules as each stage of your learning roadmap needs them. That way you’re learning the electronics rather than becoming a collector of little blue PCBs.';
