/* Outputs, actuators and driver boards — same shape as SENSOR_GROUPS.
   control = the signal it needs from the board; power = what it needs from the supply. */

const OUTPUT_RULES = [
  'A GPIO pin is a signal, not a power source — about 20mA at most.',
  'Anything with a motor, coil or many LEDs gets its own supply and a driver.',
  'Always connect the grounds of the board and the load supply together.',
];

const OUTPUT_GROUPS = [
{ n:1, title:'Light & indicators',
  intro:'From a single LED to hundreds of individually coloured pixels.',
  sensors:[
    { id:'led-out', name:'LEDs & LED bars', level:'b', control:'GPIO (PWM for brightness)', power:'2–20mA per LED',
      desc:'A GPIO pin can drive one standard LED directly through a resistor. LED bar graphs are 10 LEDs in one package, each needing its own resistor.',
      use:'Status lights, level meters, simple displays.' },
    { id:'ws2812b', name:'WS2812B / NeoPixel', level:'i', control:'1 data pin (timed 800kHz signal)', power:'5V, up to 60mA per LED at full white',
      desc:'Every LED has its own tiny controller, so hundreds can be chained on one data wire and each set to any colour. Sold as strips, rings, matrices and single pixels.',
      use:'Ambient and mood lighting, status indicators, matrix displays, costume and room effects.',
      tip:'Put 300–500Ω in the data line and 1000µF across the 5V supply. 60 LEDs can draw 3.6A — use a separate supply. From a 3.3V ESP32 the data signal is marginal; a 74AHCT125 level shifter makes it reliable.' },
    { id:'rgb-strip', name:'Analog RGB LED strip (12V)', level:'i', control:'3 PWM pins through 3 MOSFETs', power:'12V, about 1A per metre',
      desc:'Common-anode strips where the whole strip shows one colour. Each colour channel is switched by a logic-level MOSFET.',
      use:'Shelf and under-cabinet lighting, cheap whole-room colour.' },
  ] },

{ n:2, title:'Displays',
  intro:'Show numbers, text and graphics.',
  sensors:[
    { id:'tm1637', name:'TM1637 4-digit display', level:'b', control:'2 pins (CLK, DIO)', power:'3.3–5V',
      desc:'A 4-digit 7-segment module with a colon and its own driver chip. Library functions show numbers directly.',
      use:'Clocks, timers, counters, temperature readouts.' },
    { id:'max7219', name:'MAX7219 matrix / 8-digit module', level:'b', control:'3 pins (DIN, CS, CLK)', power:'5V',
      desc:'A driver chip that runs a whole 8×8 LED matrix or eight 7-segment digits, handling multiplexing and brightness. Modules chain together for scrolling text.',
      use:'Scrolling message boards, big-digit clocks, simple animations.' },
    { id:'lcd1602', name:'LCD1602 with I2C backpack', level:'b', control:'I2C (address 0x27 or 0x3F)', power:'5V',
      desc:'16 characters × 2 lines with a backlight. The PCF8574 backpack cuts the wiring down to four wires. The 20×4 LCD2004 works the same way.',
      use:'Menus, sensor readouts, status screens.',
      tip:'Only blank or solid blocks showing? Turn the blue contrast pot on the backpack.' },
    { id:'ssd1306', name:'SSD1306 OLED 0.96″ (128×64)', level:'b', control:'I2C (0x3C) or SPI', power:'3.3–5V',
      desc:'A small, sharp, high-contrast screen with no backlight, for text and simple graphics. Very low power when mostly black.',
      use:'Sensor dashboards on the device, wearables, small menus.',
      tip:'The 1.3″ version usually uses the SH1106 chip — choose the SH1106 driver or the image is shifted.' },
    { id:'tft', name:'TFT colour display (ST7735 / ST7789 / ILI9341)', level:'i', control:'SPI + DC, RST and backlight pins', power:'3.3V logic',
      desc:'Full-colour screens from 1.8″ to 3.2″. Some add a resistive touch layer (XPT2046). On the ESP32 the TFT_eSPI library is fast.',
      use:'Graphs, gauges, touch interfaces, small games.' },
    { id:'epaper', name:'E-paper (e-ink) display', level:'i', control:'SPI + BUSY, RST, DC pins', power:'3.3V, and none to hold the image',
      desc:'Looks like printed paper and keeps its image with the power off. Refreshing takes 1–15 seconds and flickers.',
      use:'Battery dashboards that update every few minutes, weather displays, shelf labels.' },
  ] },

{ n:3, title:'Sound',
  intro:'From beeps to music and voice.',
  sensors:[
    { id:'buzzer-out', name:'Active & passive buzzers', level:'b', control:'GPIO (active) or tone() / PWM (passive)', power:'3.3–5V, about 30mA',
      desc:'An active buzzer beeps on plain DC; a passive one plays whatever frequency you send it.',
      use:'Alarms, key clicks, simple melodies.',
      tip:'For a loud buzzer, switch it with a transistor instead of a pin.' },
    { id:'speaker', name:'Small speaker (4–8Ω)', level:'b', control:'Through an amplifier', power:'0.5–3W',
      desc:'Needs far more current than a GPIO pin can give — always drive it through an amplifier (or at least a transistor).',
      use:'Audio playback, voice prompts, alarms.' },
    { id:'pam8403', name:'PAM8403 amplifier', level:'i', control:'Analog audio in (DAC or filtered PWM)', power:'5V',
      desc:'A tiny class-D stereo amplifier, 2 × 3W into 4Ω speakers.',
      use:'Adding speakers to ESP32 DAC audio or any audio source.' },
    { id:'max98357a', name:'MAX98357A I2S amplifier', level:'i', control:'I2S (3 pins: BCLK, LRC, DIN)', power:'2.5–5.5V',
      desc:'Takes digital audio straight from the ESP32’s I2S port and drives a speaker at up to 3W — the cleanest ESP32 audio.',
      use:'Internet radio, voice assistants, sound effects.' },
    { id:'dfplayer', name:'DFPlayer Mini', level:'b', control:'UART (9600 baud) or buttons', power:'3.3–5V',
      desc:'Plays MP3 and WAV files from a microSD card, with a built-in 3W amplifier that drives a speaker directly.',
      use:'Talking projects, doorbells, sound boards, museum exhibits.',
      tip:'Add 1kΩ in series with its RX pin when using a 5V board, to avoid noise.' },
  ] },

{ n:4, title:'Relays & power switching',
  intro:'Let a 3.3V or 5V signal switch a much bigger load.',
  note:'Mains voltage (230V/120V) can kill. Learn switching with low-voltage DC loads, and only work on mains wiring if you are qualified.',
  sensors:[
    { id:'relay-module', name:'Relay module (1–8 channel)', level:'b', control:'1 GPIO per channel (often active-LOW)', power:'5V, about 70mA per relay coil',
      desc:'A relay with its transistor, flyback diode and indicator LED already on the board. The contacts are fully isolated from your circuit.',
      use:'Switching lamps, pumps, fans and other appliances on and off.',
      tip:'Many 5V modules are active-LOW and some won’t switch from a 3.3V pin — buy ones marked 3.3V-compatible for the ESP32.' },
    { id:'ssr', name:'Solid-state relay (SSR)', level:'i', control:'3–32V DC signal', power:'Load side: AC or DC version',
      desc:'Switches with semiconductors instead of moving contacts — silent, fast and long-lasting. It leaks a little current when off and needs a heatsink at high loads.',
      use:'Heaters, kilns and lamps switched often, PID temperature control.',
      tip:'AC SSRs only switch AC and DC SSRs only switch DC. Many cheap “25A” SSRs are fakes rated far lower.' },
    { id:'mosfet-module', name:'MOSFET switch module', level:'b', control:'GPIO or PWM', power:'DC loads, often 5–24V',
      desc:'A MOSFET on a board, for switching and dimming DC loads with PWM.',
      use:'LED strips, DC pumps, solenoids, fans, heating pads.',
      tip:'The popular IRF520 module is not logic-level — it barely turns on from 3.3V or 5V. Choose an IRLZ44N or a dual “D4184” module.' },
  ] },

{ n:5, title:'Motors & actuators',
  intro:'Make things move. Motors always need a driver and their own supply.',
  note:'For your RC car: TT gear motors with a TB6612FNG driver, an SG90 servo for steering or a sensor turret, powered from a 2S Li-ion pack through a 5V buck converter.',
  sensors:[
    { id:'tt-motor', sub:'DC motors', name:'TT gear motor', level:'b', control:'Motor driver (PWM speed + direction)', power:'3–6V, 100–250mA running, over 1A stalled',
      desc:'The yellow plastic gearmotor used on most robot-car chassis, with a 1:48 gearbox.',
      use:'2WD and 4WD robot cars, small conveyors.' },
    { id:'n20', sub:'DC motors', name:'N20 micro gear motor', level:'i', control:'Motor driver', power:'3–12V versions',
      desc:'A tiny metal-gear motor, available with a built-in magnetic encoder for measuring speed and distance.',
      use:'Small precise robots, line followers, odometry.' },
    { id:'vibration', sub:'DC motors', name:'Vibration motor', level:'b', control:'Transistor or MOSFET + diode', power:'3V, 60–100mA',
      desc:'A small motor with an off-centre weight (coin or cylinder).',
      use:'Haptic feedback, silent alarms, wearables.' },
    { id:'sg90', sub:'Servos', name:'SG90 micro servo', level:'b', control:'50Hz PWM: 1–2ms pulse ≈ 0–180°', power:'4.8–6V, up to about 650mA stalled',
      desc:'A small plastic-gear servo that moves to the angle you command and holds it.',
      use:'Steering, sensor turrets, small robot arms, latches.',
      tip:'Power servos from a separate 5V supply and connect its GND to the board’s GND — a servo on the USB 5V can reset your ESP32.' },
    { id:'mg996r', sub:'Servos', name:'MG996R metal-gear servo', level:'i', control:'50Hz PWM', power:'4.8–7.2V, up to about 2.5A stalled',
      desc:'A strong standard-size servo, around 10kg·cm, with metal gears.',
      use:'Robot arms, larger RC steering, pan-tilt heads.' },
    { id:'servo-360', sub:'Servos', name:'Continuous-rotation servo (FS90R)', level:'b', control:'50Hz PWM sets speed and direction', power:'4.8–6V',
      desc:'Looks like a servo, but the pulse width sets speed and direction instead of angle.',
      use:'Small robot wheels without a separate motor driver.' },
    { id:'28byj48', sub:'Steppers', name:'28BYJ-48 stepper + ULN2003', level:'b', control:'4 GPIO pins through the ULN2003 board', power:'5V, about 240mA',
      desc:'A cheap geared stepper that moves in exact steps — about 2048 per turn — but slowly (around 15 RPM).',
      use:'Rotating displays, blinds, dials, camera sliders.' },
    { id:'nema17', sub:'Steppers', name:'NEMA 17 stepper', level:'i', control:'STEP / DIR through a stepper driver', power:'12–24V through the driver',
      desc:'The standard bipolar stepper used in 3D printers: 200 steps per turn (1.8°), strong and precise.',
      use:'3D printers, CNC, plotters, camera sliders.' },
    { id:'bldc', sub:'Brushless', name:'Brushless motor + ESC', level:'a', control:'50Hz servo-style signal to the ESC', power:'2–4S LiPo, many amps',
      desc:'Very powerful and efficient motors. The ESC (electronic speed controller) does the complex commutation — you just send it a throttle signal.',
      use:'Drones, fast RC cars, electric skateboards.',
      tip:'Remove propellers while testing, and follow the ESC’s arming sequence.' },
    { id:'pump', sub:'Other actuators', name:'Mini water pump', level:'b', control:'MOSFET or relay', power:'3–6V submersible (100–200mA) or 12V diaphragm',
      desc:'A small DC pump — submersible or diaphragm type.',
      use:'Plant watering, fountains, coolant loops.',
      tip:'Don’t run it dry, and put a flyback diode across it.' },
    { id:'solenoid', sub:'Other actuators', name:'Solenoid / electric lock', level:'i', control:'MOSFET or relay + flyback diode', power:'Usually 12V, 0.5–1A',
      desc:'An electromagnet that pushes or pulls a plunger.',
      use:'Door locks, valves, pinball flippers, tapping mechanisms.',
      tip:'Run it in short bursts — most solenoids overheat if left energised.' },
  ] },

{ n:6, title:'Motor drivers',
  intro:'The boards that sit between your microcontroller and the motors.',
  sensors:[
    { id:'l298n', sub:'DC motor drivers', name:'L298N', level:'b', control:'ENA/ENB (PWM) + IN1–IN4', power:'5–35V motors, up to 2A per channel',
      desc:'The classic dual H-bridge board. Its old bipolar transistors lose about 2V (a 6V battery gives the motors about 4V) and get hot. It has an on-board 5V regulator, enabled by a jumper, for supplies up to 12V.',
      use:'Two DC motors or one bipolar stepper; learning H-bridges.' },
    { id:'l293d', sub:'DC motor drivers', name:'L293D', level:'b', control:'EN (PWM) + 2 inputs per motor', power:'4.5–36V, 600mA per channel',
      desc:'A dual H-bridge in a 16-pin DIP chip with built-in protection diodes.',
      use:'Learning motor control on the breadboard, small motors.' },
    { id:'tb6612', sub:'DC motor drivers', name:'TB6612FNG', level:'i', control:'PWMA/AIN1/AIN2 + PWMB/BIN1/BIN2, STBY HIGH', power:'Motors 2.5–13.5V, 1.2A per channel (3.2A peak)',
      desc:'A modern MOSFET dual H-bridge: little voltage loss, stays cool, and accepts 3.3V logic directly.',
      use:'The best choice for TT-motor robot cars with an ESP32.' },
    { id:'drv8833', sub:'DC motor drivers', name:'DRV8833', level:'i', control:'4 inputs (PWM on the inputs)', power:'2.7–10.8V, 1.5A per channel',
      desc:'A tiny, efficient dual H-bridge that works down to 2.7V.',
      use:'Small robots on 1S or 2S lithium batteries, N20 motors.' },
    { id:'bts7960', sub:'DC motor drivers', name:'BTS7960 (IBT-2)', level:'a', control:'RPWM / LPWM + enable pins', power:'5.5–27V, up to 43A',
      desc:'A single high-current H-bridge with a large heatsink.',
      use:'Big motors: large RC cars, ride-on toys, wheelchair motors.' },
    { id:'uln2003', sub:'Steppers & loads', name:'ULN2003', level:'b', control:'Up to 7 logic inputs (3.3V or 5V)', power:'Up to 50V, 500mA per channel',
      desc:'Seven Darlington transistor switches with built-in flyback diodes, all switching to ground.',
      use:'28BYJ-48 steppers, relays, solenoids and lamps from logic pins.' },
    { id:'a4988', sub:'Steppers & loads', name:'A4988', level:'i', control:'STEP + DIR (+ microstep pins)', power:'8–35V, about 1A (2A with cooling)',
      desc:'A bipolar stepper driver with up to 1/16 microstepping. Set the motor current with its small Vref pot.',
      use:'NEMA 17 steppers in printers, plotters and sliders.',
      tip:'Never unplug the motor while powered — it can destroy the driver. Put 100µF across the motor supply.' },
    { id:'drv8825', sub:'Steppers & loads', name:'DRV8825', level:'i', control:'STEP + DIR', power:'8.2–45V, up to 2.2A with cooling',
      desc:'A higher-current, pin-compatible alternative to the A4988, with up to 1/32 microstepping.',
      use:'Stronger steppers, smoother motion.' },
    { id:'tmc2209', sub:'Steppers & loads', name:'TMC2208 / TMC2209', level:'a', control:'STEP + DIR, optional UART setup', power:'Up to about 2A RMS',
      desc:'Almost silent stepper drivers (StealthChop), configurable over UART; the TMC2209 can also detect stalls.',
      use:'Quiet 3D printers, camera sliders, anything near people.' },
    { id:'pca9685', sub:'Servo & PWM', name:'PCA9685 16-channel PWM', level:'i', control:'I2C (2 pins)', power:'Logic 3.3–5V; servo power on a separate V+ terminal',
      desc:'Generates 16 independent 12-bit PWM signals over I2C, so 16 servos need only two pins. Boards can be chained.',
      use:'Robot arms, hexapods, many servos or dimmable LED channels.' },
  ] },
];

const OUTPUT_KIT = [
  { group:'Displays', ids:['ssd1306', 'lcd1602'] },
  { group:'Light', ids:['ws2812b'] },
  { group:'Sound', ids:['max98357a'] },
  { group:'Switching', ids:['relay-module', 'mosfet-module'] },
  { group:'Motors', ids:['tt-motor', 'sg90', '28byj48'] },
  { group:'Drivers', ids:['tb6612'] },
];
