/* Guided projects that combine boards, sensors and outputs.
   needs: "b:" board, "s:" sensor, "o:" output id; "a|b" = any one of them; a leading "?" = optional.
   parts: other things you need that aren’t tracked in the guides. ids are stable progress keys. */

const PROJECTS = [
{ id:'plant-monitor', title:'Plant monitor', level:'b',
  summary:'Read soil moisture, temperature and humidity, show them on an OLED and send them to your phone.',
  needs:['b:esp32-devkit|esp32-c3|esp32-s3', 's:soil-capacitive', 's:dht22|bme280|sht3x', 'o:ssd1306'],
  parts:['Breadboard and jumper wires', '10kΩ resistor (DHT22 pull-up)', 'USB cable or 5V supply'],
  learn:['Analog input (ADC)', 'Sensor calibration', 'I2C display', 'Wi-Fi + MQTT'],
  stages:[
    ['Read the soil sensor', 'Wire the capacitive sensor to 3V3, GND and GPIO 34 (an ADC1 pin). Print the raw analogRead() value to the Serial Monitor.'],
    ['Calibrate', 'Note the reading in dry air and in a glass of water. Use map() to turn the raw value into 0–100% moisture.'],
    ['Add air readings', 'Connect the DHT22 data pin to GPIO 4 with a 10kΩ pull-up — or a BME280 / SHT31 on I2C (SDA 21, SCL 22). Print temperature and humidity.'],
    ['Show it', 'Connect the SSD1306 to the same I2C pins (address 0x3C) and display all three values.'],
    ['Go online', 'Connect to Wi-Fi and publish the readings to an MQTT broker every minute. Watch them in MQTT Explorer or Home Assistant.'],
  ],
  next:['Add a pump and relay — that’s the smart irrigation project.', 'Run it on a battery with deep sleep between readings.'] },

{ id:'smart-lamp', title:'Smart ambient lamp', level:'b',
  summary:'An LED lamp with touch on/off, a brightness knob and automatic brightness that follows the room light.',
  needs:['b:esp32-devkit|esp32-c3|esp32-s3', 'o:ws2812b', 's:bh1750', 's:ttp223|cap-touch', '?s:encoder'],
  parts:['5V supply sized for the LEDs (about 60mA per LED at full white)', '1000µF capacitor', '330Ω resistor'],
  learn:['Addressable LEDs', 'Power budgeting', 'User input', 'Automation'],
  stages:[
    ['Light the strip', 'Data pin → 330Ω → strip DIN, 1000µF across the 5V supply, grounds joined. Use FastLED or Adafruit NeoPixel and cap the brightness in code.'],
    ['Touch control', 'Use a TTP223 module on any input, or the ESP32’s own touch pin (touchRead) with a piece of foil, to toggle the lamp.'],
    ['Brightness knob', 'Read the rotary encoder with interrupts to change brightness; press the knob to cycle colours.'],
    ['Automatic brightness', 'Read the BH1750 over I2C and dim the lamp as the room gets darker.'],
    ['Go online', 'Add a web page or MQTT control, and a sunrise alarm that slowly brightens in the morning.'],
  ],
  next:['Add a PIR sensor so it turns on when you walk in.'] },

{ id:'smart-irrigation', title:'Smart irrigation', level:'i',
  summary:'Water a plant automatically when the soil is dry — but never when the tank is empty or it is raining.',
  needs:['b:esp32-devkit|esp32-c3|esp32-s3', 's:soil-capacitive', 'o:pump', 'o:relay-module|mosfet-module', 's:float|water-level', '?s:rain'],
  parts:['Silicone tubing', '1N4007 diode across the pump (with a MOSFET)', 'Separate supply for the pump', 'Water container'],
  learn:['Driving loads safely', 'Hysteresis', 'Fail-safe design', 'Remote control'],
  stages:[
    ['Test the pump', 'Switch the pump with a MOSFET or relay from one GPIO. Give it its own supply, join the grounds, and fit the flyback diode.'],
    ['Water when dry', 'Turn on below about 30% moisture and off above about 45% (hysteresis stops rapid switching). Limit each run to a few seconds.'],
    ['Protect the pump', 'Read the float switch or water-level sensor and never run the pump when the tank is empty.'],
    ['Skip when raining', 'Use the rain sensor’s digital output to pause watering.'],
    ['Control & log', 'Add a web page or MQTT: see moisture, water manually, set the threshold and log every watering.'],
  ],
  next:['Several plants: one soil sensor and one valve or pump per plant.', 'Solar power for an outdoor garden.'] },

{ id:'weather-station', title:'Weather station', level:'i',
  summary:'A battery-powered outdoor station that measures temperature, humidity, pressure, light and rain.',
  needs:['b:esp32-devkit|esp32-c3', 's:bme280', 's:bh1750', 's:rain', '?s:ds18b20', '?s:uv', '?s:ina219'],
  parts:['18650 cell with a protected TP4056 charger', 'Small solar panel (optional)', 'Vented radiation shield or box'],
  learn:['Several devices on one I2C bus', 'Deep sleep', 'Battery power', 'Data logging'],
  stages:[
    ['Read the BME280', 'Connect it over I2C (SDA 21, SCL 22) and print temperature, humidity and pressure.'],
    ['Add light', 'Put the BH1750 on the same I2C bus — each device has its own address.'],
    ['Add rain', 'Read the rain board: analog value for wetness, digital output for “raining”.'],
    ['Extra sensors', 'Optional: a DS18B20 probe for ground temperature and a UV sensor on an ADC1 pin.'],
    ['Battery & deep sleep', 'Wake every 10 minutes, send the readings, sleep again. Measure the average current with the INA219 to estimate battery life.'],
    ['Dashboard', 'Send to MQTT and graph it in Node-RED, Home Assistant or ThingSpeak.'],
  ],
  next:['Wind speed with a Hall sensor and a small anemometer.', 'Compare your pressure trend with the weather forecast.'] },

{ id:'tank-monitor', title:'Water-tank monitor', level:'i',
  summary:'Show how full a water tank is, count the litres used and control the pump.',
  needs:['b:esp32-devkit|esp32-c3', 's:jsn-sr04t|hc-sr04', '?s:float', '?s:flow', '?o:relay-module'],
  parts:['1kΩ + 2kΩ resistors (divider for the 5V ECHO signal)', 'Waterproof enclosure', 'Cable to reach the tank'],
  learn:['Ultrasonic time of flight', 'Level shifting 5V → 3.3V', 'Filtering noisy data', 'Interrupts'],
  stages:[
    ['Measure the distance', 'Mount the sensor at the top of the tank facing the water. Divide the ECHO signal down to 3.3V before the ESP32.'],
    ['Convert to level', 'Water height = tank height − distance. Turn it into % full and litres from the tank’s size.'],
    ['Filter', 'Take 5 readings and use the median — ultrasonic readings jump around.'],
    ['Overflow backup', 'Add a float switch near the top as a hardware “full” alarm.'],
    ['Count usage', 'Put the flow sensor in the outlet and count its pulses with an interrupt to get litres used.'],
    ['Automate', 'Switch the fill pump with a relay: on below 20%, off at 95%, and send alerts to your phone.'],
  ],
  next:['Daily usage graphs and leak detection (flow at night).'] },

{ id:'energy-monitor', title:'Battery & energy monitor', level:'i',
  summary:'Measure voltage, current, power and energy of a battery or solar setup.',
  needs:['b:esp32-devkit|esp32-c3', 's:ina219|ina226', 's:vdiv', 'o:ssd1306'],
  parts:['A battery or solar panel to monitor', 'A test load (LED strip, motor, resistor)', 'Resistors for the divider (e.g. 100kΩ + 33kΩ)'],
  learn:['High-side current sensing', 'Power and energy', 'ADC calibration', 'Alerts'],
  stages:[
    ['Wire the INA219', 'Put it in the positive wire between the battery and the load, and connect it over I2C.'],
    ['Check it', 'Compare voltage and current with your multimeter.'],
    ['Energy', 'Add up power × time every second to get mWh used, and estimate the remaining capacity.'],
    ['Second battery', 'Measure another battery through a voltage divider on an ADC1 pin; calibrate against the multimeter.'],
    ['Display & alert', 'Show everything on the OLED, publish to MQTT, and send a low-battery alert.'],
  ],
  next:['Measure how much your other projects really use — then optimise their sleep.'] },

{ id:'security-alarm', title:'Door & motion alarm', level:'i',
  summary:'Detect a door opening or movement, arm and disarm with an RFID card, and sound an alarm.',
  needs:['b:esp32-devkit|esp32-s3', 's:reed', 's:hc-sr501|am312|pir', 's:rc522', 'o:buzzer-out', '?o:ssd1306'],
  parts:['Magnet for the reed switch', 'RFID cards or key fobs (usually included)'],
  learn:['Inputs with pull-ups', 'State machines', 'SPI', 'Notifications'],
  stages:[
    ['Door sensor', 'Reed switch between a GPIO and GND with INPUT_PULLUP: closed = LOW, door opened = HIGH.'],
    ['Motion', 'Connect the PIR output to another input — its 3.3V output is ESP32-safe. Allow it 60 seconds to settle.'],
    ['States', 'Write a state machine: disarmed → arming (30s to leave) → armed → triggered.'],
    ['RFID arm/disarm', 'Connect the RC522 over SPI (SS 5, SCK 18, MOSI 23, MISO 19, RST 27) and accept only your card IDs.'],
    ['Alarm & alerts', 'Sound the buzzer, and send a phone notification through a Telegram bot or MQTT.'],
  ],
  next:['Add more reed switches for windows, and log every event with a timestamp.'] },

{ id:'rc-car', title:'RC car / obstacle-avoiding robot', level:'a',
  summary:'A Wi-Fi controlled car that can also drive itself around obstacles.',
  needs:['b:esp32-devkit|esp32-s3', 'o:tt-motor', 'o:tb6612|drv8833|l298n', 's:hc-sr04', 'o:sg90', 's:mpu6050', '?s:tcrt5000'],
  parts:['2WD or 4WD robot chassis with wheels', '2 × 18650 in a holder (2S, 7.4V) with protection', '5V buck converter', 'Power switch'],
  learn:['H-bridge motor control', 'PWM speed', 'Battery power design', 'Wireless control', 'Sensor fusion basics'],
  stages:[
    ['Drive the motors', 'Wire the TB6612FNG: PWMA/AIN1/AIN2 and PWMB/BIN1/BIN2 to GPIOs, STBY HIGH, motor power from the battery. Write forward, back, left, right and stop.'],
    ['Power it properly', 'Battery → buck converter → 5V for the ESP32 (VIN) and the servo. Join all grounds. Test on battery, not USB.'],
    ['Remote control', 'A web-page joystick over Wi-Fi, ESP-NOW with a second ESP32 as a remote, or a Bluetooth gamepad.'],
    ['Avoid obstacles', 'Mount the HC-SR04 on the SG90 servo, scan left, centre and right, and turn towards the most free space.'],
    ['Drive straight', 'Use the MPU6050 gyro to hold a heading, and detect crashes or tipping over.'],
    ['Follow a line', 'Optional: two or three TCRT5000 sensors under the front bumper.'],
  ],
  next:['Wheel encoders for distance, a camera with an ESP32-S3, GPS for outdoor waypoints.'] },

{ id:'air-quality', title:'Room air-quality monitor', level:'a',
  summary:'Measure real CO₂ and air quality and tell you when to open a window.',
  needs:['b:esp32-devkit|esp32-s3', 's:co2', 's:sgp40|bme680', 'o:epaper|ssd1306|tft', '?o:ws2812b'],
  parts:['Enclosure with ventilation holes'],
  learn:['UART and I2C digital sensors', 'Display drivers', 'Thresholds and good UX', 'Long-term logging'],
  stages:[
    ['Real CO₂', 'Read an SCD40 (I2C) or MH-Z19B (UART) NDIR sensor. Let it run outdoors once for its baseline calibration.'],
    ['VOCs & climate', 'Add an SGP40 VOC index, or a BME680 with temperature and humidity.'],
    ['Display', 'E-paper for a clear, low-power readout, or the OLED for a quick start.'],
    ['Traffic light', 'An LED shows green below 800ppm, amber up to 1200ppm, red above — time to ventilate.'],
    ['History', 'Log to MQTT and graph a day or a week to see patterns.'],
  ],
  next:['Control a ventilation fan automatically with a MOSFET or relay.'] },

{ id:'gps-tracker', title:'GPS tracker', level:'a',
  summary:'Record where you go, show position and speed, and send your location when in Wi-Fi range.',
  needs:['b:esp32-devkit|esp32-s3', 's:neo6m|neom8n', '?o:ssd1306'],
  parts:['18650 cell with a protected TP4056 charger', 'microSD card module (for logging)', 'Clear view of the sky'],
  learn:['UART', 'NMEA parsing', 'Data logging', 'Maps'],
  stages:[
    ['Raw data', 'GPS TX → ESP32 RX2 (GPIO 16), GPS RX → TX2 (GPIO 17), 9600 baud. Print the raw NMEA sentences.'],
    ['Parse it', 'Use TinyGPSPlus to get latitude, longitude, speed, satellites and time.'],
    ['Display', 'Show position and satellite count on the OLED. Go outdoors for the first fix.'],
    ['Log', 'Save points to the microSD card as CSV or GPX and view the track on a map.'],
    ['Send', 'Upload the track over Wi-Fi when you get home — or later over LoRa or GSM.'],
  ],
  next:['Mount it on the RC car for waypoint driving.'] },
];
