/* Sensor guide for the IoT phase: 16 categories ordered simple → advanced, plus a starter collection.
   level: b = basic, i = intermediate, a = advanced. ids are stable keys for saved "have it" ticks.
   A sensor is described once, in its first category; later categories list it under `also`. */

const SENSOR_PATH = ['Individual component', 'Sensor IC', 'Sensor module', 'ESP32'];
const SENSOR_EXAMPLE = ['LDR', 'Voltage divider', 'Arduino ADC', 'ESP32 ADC', 'BH1750', 'I2C', 'MQTT', 'IoT dashboard'];

const SENSOR_GROUPS = [
{ n:1, title:'Basic sensors — start here',
  intro:'Single components you can put straight on a breadboard. Learn how each behaves electrically before you use a ready-made module.',
  learn:['Resistance', 'Voltage divider', 'Resistance vs temperature', 'Semiconductor sensing', 'Magnetic sensing', 'Simple digital sensing'],
  note:'These are excellent for component-level learning: you understand the electrical behaviour first, then a module is no longer a black box.',
  sensors:[
    { id:'ldr', name:'LDR / photoresistor', level:'b', measures:'Light', out:'Analog (voltage divider)',
      desc:'A resistor whose resistance drops as light increases — from around 1MΩ in the dark to a few hundred ohms in bright light. It reacts in tens of milliseconds.',
      use:'Night lights, automatic street lights, light-level logging, sunrise alarms.' },
    { id:'ntc', name:'NTC thermistor', level:'b', measures:'Temperature', out:'Analog (voltage divider)',
      desc:'Resistance falls as temperature rises (Negative Temperature Coefficient). A 10k NTC is 10kΩ at 25°C. The curve is not linear, so code uses the Beta or Steinhart–Hart equation.',
      use:'Room and liquid temperature, battery-pack and 3D-printer temperature, fan control.' },
    { id:'ptc', name:'PTC thermistor', level:'b', measures:'Temperature', out:'Analog / protection',
      desc:'Resistance rises with temperature (Positive Temperature Coefficient), sharply above its switch point. It is mainly used to protect circuits rather than to measure.',
      use:'Resettable fuses (polyfuses), motor and transformer overheat protection, self-regulating heaters.' },
    { id:'photodiode', name:'Photodiode', level:'b', measures:'Light', out:'Analog (µA current)',
      desc:'A diode used in reverse bias: the small leakage current rises in proportion to light. Very fast (nanoseconds to microseconds), but the current is tiny, so it needs a large resistor or an op-amp to turn it into a voltage.',
      use:'IR data links, light meters, heart-rate (pulse) sensors, beam-break detectors.' },
    { id:'phototransistor', name:'Phototransistor', level:'b', measures:'Light', out:'Analog, or digital with a comparator',
      desc:'A transistor whose base current comes from light, so it gives hundreds of times more current than a photodiode — but it responds more slowly.',
      use:'Line-following and edge sensors, optocouplers, object counters, slot encoders.' },
    { id:'ir-diode', name:'IR receiver diode', level:'b', measures:'Infrared', out:'Analog',
      desc:'A photodiode tuned to infrared (about 850–940nm), usually in dark-tinted plastic that blocks visible light. It detects raw IR level only — not remote-control codes.',
      use:'Paired with an IR LED for proximity, beam-break and object detection.',
      tip:'For TV-remote codes you need the 3-pin IR receiver module in “6. Light sensors”.' },
    { id:'hall', name:'Hall-effect sensor', level:'b', measures:'Magnetic field', out:'Analog (linear) or digital (switch)',
      desc:'Gives a voltage when a magnetic field passes through it. Linear types (e.g. 49E) output a voltage proportional to the field, centred at half the supply; switch types (e.g. A3144) simply turn on near a magnet.',
      use:'Contactless position and speed sensing, magnet detection. Current sensors like the ACS712 use it inside.' },
    { id:'reed', name:'Reed switch', level:'b', measures:'Magnetic presence', out:'Switch (use a pull-up)',
      desc:'Two metal reeds sealed in a glass tube that snap together when a magnet comes near. Needs no power at all. The glass is fragile — bend the leads away from the body.',
      use:'Door and window sensors, float switches, bicycle speedometers, tamper detection.' },
  ] },

{ n:2, title:'Temperature & environmental sensors',
  intro:'Once you understand the NTC, move on to IC-based sensors that do the conversion for you.',
  flowLabel:'Recommended progression',
  flow:['NTC', 'LM35', 'DS18B20', 'DHT22', 'BMP280', 'BME280'],
  sensors:[
    { id:'lm35', name:'LM35', level:'i', measures:'Temperature', out:'Analog',
      desc:'A precise analog sensor: 10mV per °C starting from 0V at 0°C (250mV = 25°C), about ±0.5°C accurate. It needs at least 4V supply and can’t show below 0°C without extra parts.',
      use:'Simple, accurate temperature readings on an analog pin — the natural step up from the NTC.',
      tip:'On an ESP32 power it from 5V; its output stays well below 3.3V.' },
    { id:'tmp36', name:'TMP36', level:'i', measures:'Temperature', out:'Analog',
      desc:'Also 10mV per °C, but with a 500mV offset (750mV = 25°C), so it reads from −40°C to 125°C on a single supply. Runs from 2.7–5.5V, so it works directly at 3.3V.',
      use:'Outdoor and freezer temperature where you need readings below zero.' },
    { id:'ds18b20', name:'DS18B20', level:'i', measures:'Temperature', out:'Digital (1-Wire)',
      desc:'A digital sensor, ±0.5°C, −55°C to 125°C. Each one has a unique 64-bit address, so many can share one data wire. Needs a 4.7kΩ pull-up on the data line.',
      use:'Water, soil and aquarium temperature (waterproof probe version), multi-point monitoring.' },
    { id:'dht11', name:'DHT11', level:'i', measures:'Temperature + humidity', out:'Digital (single-wire)',
      desc:'Cheap and simple: 0–50°C at ±2°C and 20–80% humidity at ±5%, one reading per second.',
      use:'First humidity experiments. Fine for learning, not for accurate measurement.' },
    { id:'dht22', name:'DHT22 / AM2302', level:'i', measures:'Temperature + humidity', out:'Digital (single-wire)',
      desc:'The better DHT: −40–80°C at ±0.5°C and 0–100% humidity at ±2–5%. One reading every 2 seconds. Runs from 3.3–6V.',
      use:'Room climate monitors, greenhouses, simple weather stations.' },
    { id:'bme280', name:'BME280', level:'i', measures:'Temperature + humidity + pressure', out:'I2C / SPI',
      desc:'A small Bosch chip that measures all three weather values accurately. Low power, 3.3V (modules usually add a regulator).',
      use:'Weather stations, indoor climate, altitude estimation.' },
    { id:'bmp280', name:'BMP280', level:'i', measures:'Temperature + pressure', out:'I2C / SPI',
      desc:'Like the BME280 but without humidity. Pressure 300–1100hPa at about ±1hPa.',
      use:'Barometers, altitude for drones and rockets, weather trends.',
      tip:'Sellers often mix up BMP280 and BME280. The chip ID tells you: 0x58 = BMP280, 0x60 = BME280.' },
    { id:'sht3x', name:'SHT30 / SHT31', level:'i', measures:'Temperature + humidity', out:'I2C',
      desc:'Sensirion sensors: around ±0.2–0.3°C and ±2% humidity, faster and more accurate than the DHT22. The SHT31 is the higher-accuracy grade.',
      use:'Accurate humidity for HVAC, storage rooms and serious weather stations.' },
  ] },

{ n:3, title:'Distance & proximity',
  intro:'Measure how far away something is, or simply whether it is there.',
  learn:['Time of flight', 'Distance calculation', 'Reflection', 'Digital/analog sensing'],
  sensors:[
    { id:'hc-sr04', name:'HC-SR04', level:'i', measures:'Distance (ultrasonic)', out:'Digital pulse (TRIG / ECHO)',
      desc:'Sends a 40kHz sound burst and times the echo. 2cm–4m range. Send a 10µs TRIG pulse, measure how long ECHO stays HIGH: distance (cm) = time (µs) ÷ 58.',
      use:'Obstacle avoidance, parking sensors, tank levels, people counting.',
      tip:'It runs on 5V and ECHO is a 5V signal — use a divider (e.g. 1kΩ/2kΩ) before an ESP32 pin.' },
    { id:'jsn-sr04t', name:'JSN-SR04T', level:'i', measures:'Distance (ultrasonic)', out:'Digital pulse',
      desc:'A waterproof ultrasonic probe on a cable. Works like the HC-SR04, but its minimum range is about 20–25cm.',
      use:'Water tank level, outdoor and vehicle sensing.' },
    { id:'vl53l0x', name:'VL53L0X', level:'i', measures:'Distance (laser time of flight)', out:'I2C',
      desc:'Times an invisible 940nm laser pulse. Millimetre resolution, up to about 1.2–2m, narrow beam, and largely unaffected by colour.',
      use:'Small robots, gesture and presence detection, precise short distances.' },
    { id:'vl53l1x', name:'VL53L1X', level:'i', measures:'Distance (laser time of flight)', out:'I2C',
      desc:'The longer-range version: up to about 4m, with an adjustable field of view.',
      use:'Room-scale presence, drone altitude hold, longer robot sensing.' },
    { id:'ir-prox', name:'IR proximity sensor', level:'b', measures:'Obstacle present', out:'Digital (adjustable threshold)',
      desc:'An IR LED, an IR receiver and an LM393 comparator on one board (e.g. FC-51). The output goes LOW when something reflects the IR, within about 2–30cm set by a pot.',
      use:'Obstacle detection on robot cars, hand detection, object counting.',
      tip:'Sunlight and black surfaces confuse it.' },
    { id:'tcrt5000', name:'IR reflective sensor (TCRT5000)', level:'b', measures:'Reflection at close range', out:'Analog or digital',
      desc:'An IR LED and a phototransistor side by side, sensing reflection from about 1–15mm. Dark surfaces reflect little, light surfaces a lot.',
      use:'Line-following robots, encoder discs, paper and edge detection.' },
  ] },

{ n:4, title:'Motion sensors',
  intro:'Detect people moving, or measure how the sensor itself moves and tilts.',
  note:'For your future RC car, the MPU6050 is particularly useful: tilt, turning rate and crash detection.',
  sensors:[
    { id:'pir', sub:'PIR', name:'PIR sensor', level:'b', measures:'Human movement (infrared change)', out:'Digital',
      desc:'A pyroelectric element behind a faceted Fresnel lens detects changes in infrared from warm, moving bodies. It cannot see a person who is sitting perfectly still, and needs 30–60s to settle after power-up.',
      use:'Motion lights, alarms, occupancy and energy-saving automation.' },
    { id:'hc-sr501', sub:'PIR', name:'HC-SR501 PIR', level:'b', measures:'Human movement', out:'Digital (3.3V HIGH)',
      desc:'The common PIR module: 4.5–20V supply, 3.3V output (safe for ESP32), with pots for range (about 3–7m) and on-time (0.3s–5min) and a jumper for single or repeat trigger.',
      use:'Room motion detection, security lights, doorbells.' },
    { id:'am312', sub:'PIR', name:'AM312 PIR', level:'b', measures:'Human movement', out:'Digital',
      desc:'A tiny PIR that runs from 2.7–12V and draws very little current, with a short fixed on-time and no adjustments.',
      use:'Battery-powered and small enclosures, wearable or hidden sensors.' },
    { id:'adxl345', sub:'Accelerometer', name:'ADXL345', level:'i', measures:'Acceleration (3-axis)', out:'I2C / SPI',
      desc:'Measures acceleration and tilt on three axes, ±2 to ±16g, with built-in tap, double-tap, free-fall and activity interrupts.',
      use:'Tilt sensing, vibration monitoring, step counting, drop detection.' },
    { id:'mpu6050', sub:'Accelerometer', name:'MPU6050', level:'i', measures:'Acceleration + rotation (6-axis)', out:'I2C',
      desc:'A 3-axis accelerometer plus a 3-axis gyroscope. The gyro drifts over time and the accelerometer is noisy, so they are combined (complementary or Kalman filter) for a stable angle. Also counts as an entry-level IMU.',
      use:'Self-balancing robots, RC car tilt and turn rate, gesture control, crash detection.' },
    { id:'lis3dh', sub:'Accelerometer', name:'LIS3DH', level:'i', measures:'Acceleration (3-axis)', out:'I2C / SPI',
      desc:'A very low-power accelerometer (±2 to ±16g) with wake-on-motion interrupts.',
      use:'Battery wearables, asset trackers that sleep until moved.' },
    { id:'mpu9250', sub:'IMU', name:'MPU9250', level:'a', measures:'Acceleration + rotation + magnetic field (9-axis)', out:'I2C / SPI',
      desc:'An MPU6050-style chip plus a magnetometer, so it can also find heading.',
      use:'Drones, head tracking, orientation with compass heading.',
      tip:'The chip is discontinued. Many boards sold as MPU9250 are clones, or MPU6500s with no magnetometer.' },
    { id:'bno055', sub:'IMU', name:'BNO055', level:'a', measures:'Absolute orientation (9-axis)', out:'I2C / UART',
      desc:'Accelerometer, gyro and magnetometer with a built-in processor that does the sensor fusion and outputs ready-made angles (Euler or quaternion).',
      use:'Robot and camera orientation, VR and motion capture — without writing fusion code.',
      tip:'It needs a short calibration after each power-up.' },
  ] },

{ n:5, title:'Magnetic sensors',
  intro:'Sense magnets and magnetic fields — from a simple on/off switch to a full compass.',
  learnLabel:'Applications',
  learn:['Wheel rotation', 'RPM measurement', 'Door detection', 'Position detection', 'Compass'],
  also:['hall', 'reed'],
  sensors:[
    { id:'a3144', sub:'Hall-effect sensor', name:'A3144 Hall sensor', level:'b', measures:'Magnet present (south pole)', out:'Digital (open collector)',
      desc:'A Hall-effect switch: the output pulls LOW when the south pole of a magnet is near its marked face. Open-collector, so it needs a 10kΩ pull-up. Supply 4.5–24V.',
      use:'Wheel rotation and RPM counting (magnet on the wheel), end-stops, position detection.',
      tip:'On an ESP32, power it from 5V and connect the pull-up to 3.3V.' },
    { id:'hmc5883l', sub:'Magnetometer', name:'HMC5883L', level:'a', measures:'Magnetic field / heading (3-axis)', out:'I2C',
      desc:'A 3-axis magnetometer used as a digital compass.',
      use:'Compass heading for robots, drones and GPS navigation.',
      tip:'The genuine Honeywell chip is discontinued — most cheap “HMC5883L” boards actually carry a QMC5883L.' },
    { id:'qmc5883l', sub:'Magnetometer', name:'QMC5883L', level:'a', measures:'Magnetic field / heading (3-axis)', out:'I2C',
      desc:'The common replacement compass chip. It has a different I2C address (0x0D) and registers, so it needs a QMC library.',
      use:'Compass heading, as above.',
      tip:'Keep it away from motors, speakers and steel, and calibrate it (hard- and soft-iron) in its final position.' },
  ] },

{ n:6, title:'Light sensors',
  intro:'From simple light level to calibrated lux and invisible light.',
  flowLabel:'Start with',
  flow:['LDR', 'Photodiode', 'BH1750'],
  also:['ldr', 'photodiode', 'phototransistor', 'ir-diode'],
  sensors:[
    { id:'ir-receiver', name:'IR receiver module (VS1838B / TSOP38238)', level:'b', measures:'Modulated infrared (38kHz)', out:'Digital',
      desc:'A 3-pin module with a photodiode, amplifier and 38kHz demodulator inside. Its output goes LOW when it sees IR flashing at 38kHz, and it ignores steady light.',
      use:'Decoding TV-remote buttons to control your own projects.' },
    { id:'uv', name:'UV sensor (GUVA-S12SD / ML8511)', level:'i', measures:'Ultraviolet light', out:'Analog',
      desc:'A photodiode sensitive to UV-A/UV-B with an amplifier. The output voltage is roughly proportional to the UV index.',
      use:'UV index for weather stations, sun-exposure warnings, UV-curing checks.' },
    { id:'als', name:'Ambient light sensor', level:'i', measures:'Light (lux)', out:'I2C',
      desc:'A photodiode and ADC in one chip, filtered to match human vision, reporting real lux values. BH1750, TSL2561 and VEML7700 are examples.',
      use:'Automatic screen and lamp brightness, daylight logging.' },
    { id:'bh1750', name:'BH1750', level:'i', measures:'Light (1–65535 lux)', out:'I2C',
      desc:'Gives light in lux directly over I2C with no calibration. 16-bit, simple to use.',
      use:'Smart lighting, plant-growth monitoring, the “sensor IC” step after the LDR.' },
    { id:'tsl2561', name:'TSL2561', level:'i', measures:'Light (0.1–40,000 lux)', out:'I2C',
      desc:'Has two photodiodes (visible + IR and IR only) and subtracts them, so lux readings stay accurate under different light sources.',
      use:'Accurate lux measurement, lighting under mixed sunlight and lamps.' },
  ] },

{ n:7, title:'Gas & air-quality sensors',
  intro:'For later. Most cheap gas sensors show trends and alarms, not precise ppm values.',
  note:'Be careful with MQ sensors: each has a heater that draws about 150mA at 5V, needs 24–48 hours of burn-in and minutes of warm-up, and must be calibrated in clean air. They are not plug-and-play precision instruments — and never a replacement for a certified alarm.',
  sensors:[
    { id:'mq2', sub:'MQ series', name:'MQ-2', level:'a', measures:'Smoke, LPG, propane, hydrogen, methane', out:'Analog + digital',
      desc:'A heated tin-dioxide element whose resistance drops in combustible gases or smoke. The module adds a comparator for a digital alarm output.',
      use:'General smoke and combustible-gas detection demos.' },
    { id:'mq3', sub:'MQ series', name:'MQ-3', level:'a', measures:'Alcohol (ethanol) vapour', out:'Analog + digital',
      desc:'Tuned for alcohol, with low sensitivity to petrol and smoke.',
      use:'Breath-alcohol demos (not a legal breathalyser), fermentation monitoring.' },
    { id:'mq4', sub:'MQ series', name:'MQ-4', level:'a', measures:'Methane (natural gas, CNG)', out:'Analog + digital',
      desc:'High sensitivity to methane.',
      use:'Natural-gas and biogas leak detection.' },
    { id:'mq5', sub:'MQ series', name:'MQ-5', level:'a', measures:'LPG, natural gas, town gas', out:'Analog + digital',
      desc:'Sensitive to LPG and natural gas.',
      use:'Kitchen gas-leak alarms.' },
    { id:'mq6', sub:'MQ series', name:'MQ-6', level:'a', measures:'LPG (propane, butane)', out:'Analog + digital',
      desc:'Most sensitive to LPG, with little response to alcohol or smoke.',
      use:'LPG cylinder leak detection.' },
    { id:'mq7', sub:'MQ series', name:'MQ-7', level:'a', measures:'Carbon monoxide (CO)', out:'Analog + digital',
      desc:'Detects CO, but only reads correctly with a cycled heater: 5V for 60s, then 1.4V for 90s.',
      use:'Learning about CO detection. For real safety use a certified CO alarm.' },
    { id:'mq135', sub:'MQ series', name:'MQ-135', level:'a', measures:'Air-quality gases (NH₃, NOx, benzene, smoke, CO₂)', out:'Analog + digital',
      desc:'Responds to many pollutants together, so it shows a general air-quality trend. It cannot give a true CO₂ reading.',
      use:'Indoor air-quality trend indicators, ventilation reminders.' },
    { id:'ccs811', sub:'Digital air-quality sensors', name:'CCS811', level:'a', measures:'eCO₂ + TVOC', out:'I2C',
      desc:'A digital metal-oxide sensor that reports estimated CO₂ (eCO₂) and total VOCs. Needs a 20-minute warm-up. Now discontinued.',
      use:'Indoor air-quality monitors.' },
    { id:'sgp30', sub:'Digital air-quality sensors', name:'SGP30', level:'a', measures:'TVOC + eCO₂', out:'I2C',
      desc:'Sensirion multi-pixel gas sensor. Store and restore its baseline and feed it humidity for good results.',
      use:'Air purifiers, smart ventilation.' },
    { id:'sgp40', sub:'Digital air-quality sensors', name:'SGP40', level:'a', measures:'VOC index (0–500)', out:'I2C',
      desc:'Outputs a VOC index through Sensirion’s algorithm — relative “better or worse than usual” air.',
      use:'Air-quality indicators, purifier automation. The SGP41 adds NOx.' },
    { id:'bme680', sub:'Digital air-quality sensors', name:'BME680', level:'a', measures:'Temperature, humidity, pressure + gas (VOC)', out:'I2C / SPI',
      desc:'A BME280 with an added gas-resistance sensor. Bosch’s BSEC library turns it into an indoor air-quality (IAQ) index.',
      use:'All-in-one environment and air-quality stations.' },
    { id:'bme688', sub:'Digital air-quality sensors', name:'BME688', level:'a', measures:'Temperature, humidity, pressure + gas scanning', out:'I2C / SPI',
      desc:'A BME680 whose gas heater can scan temperature profiles, and be trained with Bosch AI-Studio to recognise specific gas “fingerprints”.',
      use:'Advanced projects: detecting spoiled food, specific smells or leaks.' },
  ] },

{ n:8, title:'Soil & water sensors',
  intro:'Measure moisture, water level, flow and water quality.',
  learnLabel:'Useful for building',
  learn:['Smart irrigation', 'Water tank monitoring', 'Leak detection', 'Weather station'],
  sensors:[
    { id:'soil-resistive', name:'Soil moisture sensor (resistive)', level:'b', measures:'Soil moisture', out:'Analog + digital',
      desc:'Two exposed metal probes measure how well the soil conducts electricity. Cheap, but the probes corrode quickly through electrolysis.',
      use:'Learning and short experiments.',
      tip:'Power it from a GPIO pin only while taking a reading — it lasts much longer.' },
    { id:'soil-capacitive', name:'Capacitive soil moisture sensor', level:'b', measures:'Soil moisture', out:'Analog',
      desc:'Measures the change in capacitance of the soil, with no exposed metal, so it doesn’t corrode.',
      use:'Long-term smart irrigation and plant monitoring.',
      tip:'Calibrate it: note the reading in dry air and in a glass of water, then map between them.' },
    { id:'water-level', name:'Water-level sensor', level:'b', measures:'Water depth (a few cm)', out:'Analog',
      desc:'A strip of exposed parallel traces. The more of it is under water, the higher the reading.',
      use:'Demos, cup and small-container levels. It corrodes, so it is not for permanent installs.' },
    { id:'float', name:'Float switch', level:'b', measures:'Water level (high/low)', out:'Switch',
      desc:'A float with a magnet slides along a stem and operates a reed switch inside. Simple, reliable, no power needed.',
      use:'Tank full/empty detection, sump pumps, aquarium top-up.' },
    { id:'leak', name:'Water-leak sensor', level:'b', measures:'Water present', out:'Digital',
      desc:'Probes that lie on the floor; water bridging them triggers the output.',
      use:'Alerts under water tanks, washing machines and pipes.' },
    { id:'rain', name:'Rain sensor', level:'b', measures:'Rain / wetness', out:'Analog + digital',
      desc:'A rain board with interleaved traces plus an LM393 comparator module (FC-37 / YL-83), giving an analog wetness value and a digital threshold output.',
      use:'Weather stations, closing windows or covers, pausing irrigation.' },
    { id:'flow', name:'Water-flow sensor (YF-S201)', level:'i', measures:'Water flow rate', out:'Digital pulses',
      desc:'Water spins a small turbine with a magnet; a Hall sensor inside outputs pulses. For the YF-S201: flow (L/min) = pulse frequency (Hz) ÷ 7.5, about 450 pulses per litre.',
      use:'Water-usage meters, tank-fill monitoring, irrigation flow checks.',
      tip:'Count the pulses with an interrupt pin.' },
    { id:'ph', name:'pH sensor', level:'a', measures:'Acidity / alkalinity (pH 0–14)', out:'Analog',
      desc:'A glass-electrode probe with an amplifier board (e.g. PH-4502C). Must be calibrated with pH 4 and pH 7 buffer solutions, and the probe must be stored wet.',
      use:'Hydroponics, aquariums, pools, soil testing.' },
    { id:'tds', name:'TDS sensor', level:'i', measures:'Total dissolved solids (ppm)', out:'Analog',
      desc:'Measures water conductivity and converts it to ppm of dissolved solids. Readings need temperature compensation — pair it with a DS18B20.',
      use:'Drinking-water and RO filter checks, hydroponic nutrients, aquariums.' },
    { id:'turbidity', name:'Turbidity sensor', level:'i', measures:'Water cloudiness (NTU)', out:'Analog + digital',
      desc:'Shines light through the water and measures how much is scattered. The voltage falls as the water gets cloudier.',
      use:'Water-quality monitoring, filter checks, washing-machine rinse detection.' },
  ] },

{ n:9, title:'Pressure sensors',
  intro:'Air pressure for weather and altitude, and gauge pressure for liquids and air lines.',
  learnLabel:'Useful for',
  learn:['Altitude', 'Weather', 'Air pressure', 'Pneumatic systems'],
  also:['bmp280', 'bme280'],
  sensors:[
    { id:'bmp180', name:'BMP180', level:'i', measures:'Temperature + barometric pressure', out:'I2C',
      desc:'The older Bosch barometer, now replaced by the more accurate, lower-power BMP280. Still common in kits.',
      use:'Barometer and altitude experiments.' },
    { id:'mpx', name:'MPX series pressure sensors', level:'a', measures:'Gauge / differential / absolute pressure', out:'Analog',
      desc:'NXP pressure transducers with a hose port, e.g. MPX5010DP (0–10kPa differential) or MPX5700AP (up to 700kPa absolute). 5V supply, analog output.',
      use:'Tank level from air pressure, pneumatic systems, airflow and filter blockage.' },
    { id:'baro', name:'Barometric pressure sensors', level:'i', measures:'Absolute air pressure', out:'I2C / SPI',
      desc:'Measure the pressure of the air around them. Near sea level, pressure falls about 12Pa (0.12hPa) for every metre you climb, and falling pressure over hours means worsening weather. Examples: BMP280, BME280, MS5611 (very high resolution).',
      use:'Altitude and floor detection, weather forecasting, drone altitude hold.' },
  ] },

{ n:10, title:'Sound sensors',
  intro:'Turn sound into a signal you can measure and process.',
  flowLabel:'Learn',
  flow:['Sound', 'Electrical signal', 'Amplification', 'ADC', 'Digital processing'],
  note:'Start with the individual electret microphone before using modules — biasing and amplifying it yourself teaches how audio signals work.',
  sensors:[
    { id:'electret', name:'Electret microphone', level:'b', measures:'Sound', out:'Analog (millivolts, AC)',
      desc:'A capsule with a tiny built-in transistor. It needs a bias resistor (2.2–10kΩ) from the supply and a coupling capacitor, and its millivolt output must be amplified (e.g. with your LM358) before an ADC can use it.',
      use:'Clap switches, sound-level meters, learning audio amplifiers.' },
    { id:'mems-mic', name:'MEMS microphone', level:'i', measures:'Sound', out:'Analog, PDM or I2S',
      desc:'The tiny silicon microphones used in phones. Very consistent and low-power; available with analog or digital outputs.',
      use:'Voice capture, noise monitoring, compact devices.' },
    { id:'max9814', name:'MAX9814', level:'i', measures:'Sound', out:'Analog',
      desc:'An electret microphone module with an amplifier and automatic gain control (40/50/60dB), so both quiet and loud sounds come out at a usable level.',
      use:'Sound-level detection, audio-reactive LEDs, simple recording.' },
    { id:'inmp441', name:'INMP441', level:'a', measures:'Sound', out:'I2S (digital)',
      desc:'A 24-bit digital MEMS microphone that connects straight to the ESP32’s I2S interface — no analog noise problems.',
      use:'Voice recording, speech recognition, FFT spectrum displays, noise meters.' },
    { id:'sph0645', name:'SPH0645', level:'a', measures:'Sound', out:'I2S (digital)',
      desc:'Another I2S digital MEMS microphone (Knowles), filling the same role as the INMP441. Runs at 3.3V.',
      use:'ESP32 audio projects.' },
  ] },

{ n:11, title:'Touch sensors',
  intro:'Detect a finger through capacitance or pressure.',
  note:'The ESP32 itself has up to 10 capacitive touch pins (touchRead()), so you can make touch buttons with just a piece of foil or wire.',
  sensors:[
    { id:'cap-touch', name:'Capacitive touch sensor', level:'b', measures:'Touch / proximity', out:'Digital',
      desc:'An electrode forms a small capacitor; your finger adds capacitance, and the controller detects the change — even through a few millimetres of plastic or glass.',
      use:'Buttons with no moving parts, sealed control panels, touch lamps.' },
    { id:'ttp223', name:'TTP223', level:'b', measures:'Touch (1 pad)', out:'Digital',
      desc:'A single touch-pad module, 2–5.5V. Solder jumpers choose momentary or toggle output, and active HIGH or LOW.',
      use:'Replacing push buttons, hidden touch switches.' },
    { id:'mpr121', name:'MPR121', level:'i', measures:'Touch (12 electrodes)', out:'I2C',
      desc:'A 12-channel capacitive touch controller with an interrupt pin. Electrodes can be foil, conductive paint or even fruit.',
      use:'Touch keypads, touch pianos, interactive art.' },
    { id:'resistive-touch', name:'Resistive touch sensors', level:'i', measures:'Touch position / force', out:'Analog',
      desc:'Two conductive layers pressed together — resistive touchscreens read X/Y position with the ADC. Force-sensing resistors (FSRs) drop in resistance as you press harder.',
      use:'Touch displays, pressure pads, grip and weight sensing.' },
  ] },

{ n:12, title:'Position & movement sensors',
  intro:'Know where a shaft, slider or axis is — important for robotics and your RC work.',
  also:['hall', 'reed'],
  sensors:[
    { id:'encoder', name:'Rotary encoder (KY-040)', level:'b', measures:'Rotation steps + direction', out:'Digital (A/B quadrature)',
      desc:'Turns endlessly and outputs two offset pulse trains (A and B); which one leads tells you the direction. Most have about 20 clicks per turn and a push switch.',
      use:'Menus and volume knobs, setting values, manual control.',
      tip:'Use pull-ups and debounce in code, or read it with interrupts.' },
    { id:'pot-sensor', name:'Potentiometer', level:'b', measures:'Absolute angle (about 270°)', out:'Analog',
      desc:'A voltage divider with a moving wiper, so the voltage tells you the exact position — even right after power-up. Joysticks are two pots.',
      use:'Knobs, joysticks, servo position feedback.' },
    { id:'linear-pot', name:'Linear potentiometer', level:'b', measures:'Linear position', out:'Analog',
      desc:'A potentiometer with a straight track and a slider.',
      use:'Mixer-style faders, linear position of an axis or actuator.' },
    { id:'limit', name:'Limit switch', level:'b', measures:'End of travel', out:'Switch (COM / NO / NC)',
      desc:'A lever-operated microswitch that snaps when something reaches it. Use NC (normally closed) wiring so a broken wire is detected as “triggered”.',
      use:'End-stops for robot arms, 3D printers, CNC and sliding gates.' },
    { id:'optical-encoder', name:'Optical encoder', level:'i', measures:'Rotation speed / distance', out:'Digital pulses',
      desc:'A slotted disc passes through an IR slot sensor (e.g. an H206 / LM393 speed module), giving one pulse per slot. Industrial encoders give thousands of pulses per turn with direction.',
      use:'Wheel speed and odometry for robot cars, motor RPM.' },
  ] },

{ n:13, title:'Current & voltage sensing',
  intro:'Extremely important for IoT and robotics — especially battery-powered projects.',
  flowLabel:'You will eventually build',
  flow:['Battery', 'Current measurement', 'ESP32', 'Voltage / current / power', 'Dashboard'],
  sensors:[
    { id:'acs712', sub:'Current', name:'ACS712', level:'i', measures:'Current, AC or DC (±5 / 20 / 30A)', out:'Analog',
      desc:'A Hall-effect sensor: the current path is electrically isolated from the output. The output sits at 2.5V for 0A and moves 185, 100 or 66mV per amp depending on the version. Noisy at small currents.',
      use:'Motor current, appliance power monitoring.',
      tip:'It needs 5V and its output can swing to 5V — divide it before an ESP32 pin.' },
    { id:'acs758', sub:'Current', name:'ACS758', level:'a', measures:'High current (50–200A)', out:'Analog',
      desc:'The heavy-duty Hall-effect current sensor, with a thick copper conductor.',
      use:'Big motors, solar systems, e-bikes, battery banks.' },
    { id:'ina219', sub:'Current', name:'INA219', level:'i', measures:'Current + bus voltage + power', out:'I2C',
      desc:'Measures the voltage across a small shunt resistor on the high side, plus the load voltage (up to 26V). Modules with a 0.1Ω shunt read up to ±3.2A, and the chip calculates power.',
      use:'Battery and solar monitoring, measuring how much your ESP32 project draws.' },
    { id:'ina226', sub:'Current', name:'INA226', level:'a', measures:'Current + bus voltage + power', out:'I2C',
      desc:'A more precise INA219: 16-bit, up to 36V, with an alert pin for over-current or under-voltage.',
      use:'Accurate battery gauges, power logging, protection alarms.' },
    { id:'vdiv', sub:'Voltage', name:'Voltage divider', level:'b', measures:'Voltage', out:'Analog',
      desc:'Two resistors scale a higher voltage down to your ADC range: Vout = Vin × R2 ÷ (R1 + R2). For example 100kΩ over 33kΩ turns a 12.6V battery into about 3.1V for an ESP32.',
      use:'Battery voltage monitoring, solar panel voltage.',
      tip:'The ESP32 ADC is non-linear near 0V and 3.3V — calibrate against your multimeter.' },
  ],
  alsoLabel:'Also used for voltage',
  also:['ina219', 'ina226'] },

{ n:14, title:'Gas / flame / safety',
  intro:'Detecting fire and dangerous gases. For later.',
  note:'For serious CO₂ or air-quality measurement, use dedicated digital sensors rather than treating MQ modules as precision instruments — and never rely on a hobby build instead of a certified smoke or CO alarm.',
  also:['mq2', 'mq7', 'mq135', 'sgp40', 'bme680'],
  alsoLabel:'MQ-series and VOC sensors from section 7',
  sensors:[
    { id:'flame', name:'Flame sensor', level:'b', measures:'Flame (IR 760–1100nm)', out:'Analog + digital',
      desc:'An IR-sensitive photodiode or phototransistor with an LM393 comparator. Detects a candle or lighter flame within about 1m. Sunlight and hot lamps trigger it too.',
      use:'Fire-fighting robot demos, flame-presence indicators.' },
    { id:'smoke', name:'Smoke sensor', level:'a', measures:'Smoke', out:'Analog / digital',
      desc:'Real smoke alarms use optical scattering (a light beam that smoke particles reflect) or ionisation. In Arduino kits “smoke sensor” usually means the MQ-2 gas sensor.',
      use:'Smoke-detection experiments and alerts alongside a proper alarm.' },
    { id:'co', name:'CO sensor (electrochemical)', level:'a', measures:'Carbon monoxide (ppm)', out:'Analog / UART',
      desc:'Electrochemical cells (e.g. Winsen ZE07-CO) give real ppm readings at low power, unlike the heated MQ-7.',
      use:'Garage and boiler-room CO monitoring (alongside a certified alarm).' },
    { id:'co2', name:'CO₂ sensor (NDIR)', level:'a', measures:'Carbon dioxide (ppm)', out:'UART / I2C / PWM',
      desc:'True CO₂ sensors measure infrared absorption (NDIR) or use photoacoustics: MH-Z19B, Sensirion SCD30 and SCD40/41. The “eCO₂” from CCS811 or SGP30 is only an estimate from VOCs.',
      use:'Classroom and office ventilation monitors (above ~1000ppm, open a window), greenhouses.' },
    { id:'voc', name:'VOC sensor', level:'a', measures:'Volatile organic compounds', out:'I2C',
      desc:'Metal-oxide sensors that respond to paint, cleaning products, cooking and breath. They give a relative index, not the amount of any single chemical.',
      use:'Air purifier automation, indoor air-quality dashboards.' },
  ] },

{ n:15, title:'GPS / location',
  intro:'For when you start IoT and robotics projects that move.',
  flowLabel:'Learn',
  flow:['GPS', 'UART', 'NMEA data', 'ESP32', 'Location'],
  sensors:[
    { id:'neo6m', name:'NEO-6M GPS', level:'i', measures:'Position, speed, time', out:'UART (9600 baud, NMEA)',
      desc:'The classic u-blox 6 GPS module. Sends NMEA text sentences such as $GPGGA and $GPRMC. About 2.5m accuracy with a clear sky; the first fix can take 30s or more outdoors, and the backup battery speeds up later starts.',
      use:'Trackers, logging RC car routes, clocks synced to GPS time.' },
    { id:'neom8n', name:'NEO-M8N', level:'i', measures:'Position, speed, time', out:'UART / I2C',
      desc:'Receives several satellite systems at once (GPS + GLONASS / Galileo / BeiDou), so it fixes faster and more reliably, at up to 10 updates per second. Drone versions often include a compass.',
      use:'Drones, rovers, more reliable tracking.' },
    { id:'ublox', name:'u-blox GNSS modules', level:'a', measures:'Position (down to cm with RTK)', out:'UART / I2C / SPI',
      desc:'The family behind the modules above, e.g. MAX-M10S (very low power) and ZED-F9P (RTK — centimetre accuracy with correction data). Configure them with u-center; they speak NMEA and the binary UBX protocol.',
      use:'Precision robotics, surveying, autonomous mowers.' },
  ] },

{ n:16, title:'RFID / identification',
  intro:'Not exactly sensors, but very useful IoT inputs.',
  learn:['SPI', 'I2C', 'NFC', 'RFID'],
  sensors:[
    { id:'rc522', name:'RC522 RFID', level:'i', measures:'13.56MHz cards and tags', out:'SPI',
      desc:'Reads and writes MIFARE Classic cards and key fobs at up to about 3cm.',
      use:'Door locks, attendance systems, tap-to-start projects.',
      tip:'It is a 3.3V module — do not power it from 5V.' },
    { id:'pn532', name:'PN532 NFC', level:'i', measures:'NFC / 13.56MHz tags', out:'I2C / SPI / UART',
      desc:'A full NFC controller: reads and writes MIFARE and NTAG tags and can talk to phones. Switches on the board select the interface.',
      use:'Phone-tap interactions, NFC tag readers and writers, smart-card projects.' },
    { id:'nfc', name:'NFC modules & tags', level:'b', measures:'Identification', out:'—',
      desc:'Stickers, cards and key rings (e.g. NTAG213/215/216) that store an ID or a small message such as a URL, readable by any NFC phone.',
      use:'Tap-to-open links, labelling equipment, home-automation triggers.',
      tip:'125kHz RFID cards (EM4100, read by the RDM6300) are a different system — they don’t work with the RC522 or PN532.' },
  ] },
];

/* 17. The recommended collection: don't buy everything above, start with these. */
const SENSOR_KIT = [
  { group:'Basic', ids:['ldr', 'ntc', 'photodiode', 'phototransistor', 'a3144', 'reed'] },
  { group:'Temperature', ids:['lm35', 'ds18b20', 'dht22'] },
  { group:'Environment', ids:['bmp280', 'bme280'] },
  { group:'Distance', ids:['hc-sr04', 'vl53l0x'] },
  { group:'Motion', ids:['pir', 'adxl345', 'mpu6050'] },
  { group:'Light', ids:['bh1750'] },
  { group:'Sound', ids:['electret'] },
  { group:'Soil / water', ids:['soil-capacitive', 'water-level', 'flow', 'rain'] },
  { group:'Current / power', ids:['ina219'] },
  { group:'Position', ids:['encoder', 'limit'] },
  { group:'Identification', ids:['rc522', 'pn532'] },
  { group:'Location', ids:['neo6m'] },
];
